// Real UI and API; local providers stay off. Supports Vite for pre-build review.
const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),os=require('os'),{spawn,execFileSync}=require('child_process'),assert=require('assert/strict');
const root=path.resolve(__dirname,'../..'),data=fs.mkdtempSync(path.join(os.tmpdir(),'sf-combined-')),base='http://127.0.0.1:8097',front=process.env.SF_BROWSER_DEV?'http://127.0.0.1:8197':base;
let server,dev,browser,logs='';const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function ready(url){for(let i=0;i<150;i++){try{if((await fetch(url)).ok)return;}catch{}await wait(100);}throw Error('Server unavailable '+url+' '+logs.slice(-1200));}
async function api(url,body,method='POST'){const r=await fetch(base+'/api'+url,{method,headers:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});assert(r.ok,await r.clone().text());return r.json();}
async function upload(pid,file){const form=new FormData();form.append('file',new Blob([fs.readFileSync(file)]),path.basename(file));const r=await fetch(base+'/api/assets/upload?project_id='+pid,{method:'POST',body:form});assert(r.ok,await r.clone().text());return r.json();}
(async()=>{try{
 server=spawn('python',['-m','uvicorn','app.main:app','--host','127.0.0.1','--port','8097'],{cwd:path.join(root,'backend'),env:{...process.env,SCENEFORGE_DATA_DIR:data}});server.stderr.on('data',d=>logs+=d);server.stdout.on('data',d=>logs+=d);await ready(base+'/api/health');
 if(process.env.SF_BROWSER_DEV){dev=spawn(process.execPath,[path.join(root,'frontend/node_modules/vite/bin/vite.js'),'--config','vite.browser-tests.config.ts','--host','127.0.0.1','--port','8197'],{cwd:path.join(root,'frontend'),env:{...process.env,SF_DEV_BACKEND:base}});dev.stderr.on('data',d=>logs+=d);await ready(front);}
 let p=await api('/projects',{title:'Combined tools review',aspect:'16:9'});p=await api('/projects/'+p.id,undefined,'GET');const pid=p.id,sid=p.scenes[0].id,initialIds=p.scenes.map(s=>s.id);
 const movie=path.join(root,'examples/fixture_assets/clip1.mp4'),photo=await upload(pid,path.join(root,'examples/fixture_assets/image1.png')),video=await upload(pid,movie);
 await api('/scenes/'+sid+'/shots',{asset_id:video.id});await api('/scenes/'+sid,{timing_mode:'fixed',requested_duration_ms:8000,subtitle_text:'Hello world',font:{captions_enabled:true,caption_segments:[{id:'sample-cap',text:'Hello world',start_ms:1000,end_ms:2000}]}},'PATCH');
 const wav=path.join(data,'recording.wav');execFileSync('ffmpeg',['-y','-v','error','-f','lavfi','-i','sine=frequency=300:sample_rate=16000:duration=2',wav]);const form=new FormData();form.append('file',new Blob([fs.readFileSync(wav)]),'recording.wav');const take=await(await fetch(base+'/api/scenes/'+sid+'/voice-takes/upload',{method:'POST',body:form})).json();
 await api('/projects/'+pid,{finishing:{audio_clips:[{id:'music-clip',asset_id:take.audio_asset_id,name:'Recording',start_ms:0,source_in_ms:0,source_out_ms:2000,source_duration_ms:2000,volume:100,fade_in_ms:0,fade_out_ms:0,mute:false}],music:{asset_id:take.audio_asset_id,volume:35,duck:70,fade_in_ms:0,fade_out_ms:0}}},'PATCH');
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(front);await page.getByRole('button',{name:/Combined tools review Open project/}).click();await page.getByRole('button',{name:'Skip tour',exact:true}).click();
 const read=()=>api('/projects/'+pid,undefined,'GET');async function saved(fn){const apply=page.locator(".scene-editor:not([hidden]) .editor-draft-actions").getByRole("button",{name:"Apply changes",exact:true});if(await apply.count()&&await apply.isEnabled())await apply.click();for(let i=0;i<100;i++){p=await read();if(fn(p)){await page.locator('.save-status').filter({hasText:'All changes saved'}).waitFor();return p;}await wait(100);}throw Error('Edit not saved');}
 async function seek(ms){await page.evaluate(ms=>window.dispatchEvent(new CustomEvent('sceneforge-timeline-seek',{detail:{timeMs:ms}})),ms);}
 await seek(1000);const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Add video at playhead',exact:true}).click();await(await chooser).setFiles(movie);p=await saved(p=>p.finishing_json.layer_clips?.length===1);const layer=p.finishing_json.layer_clips[0];assert.equal(layer.kind,'video');assert.equal(layer.start_ms,1000);assert.equal(p.scenes[0].shots.length,1);await page.getByRole('heading',{name:'Video clip',exact:true}).waitFor();assert(await page.getByRole('checkbox',{name:'Mute video layer',exact:true}).isChecked());
 const companion=page.locator('[data-companion-preview] .layer-draft-preview');await companion.waitFor();const draftBox=await companion.boundingBox(),mainBox=await page.locator('.scene-editor:not([hidden]) .canvas-viewport').boundingBox();assert(draftBox.x>mainBox.x+mainBox.width-2);await page.getByRole('button',{name:'Minimize draft preview',exact:true}).click();assert.equal(await companion.count(),0);await page.locator('[data-companion-preview]').getByRole('button',{name:'Restore draft preview',exact:true}).click();await companion.waitFor();await page.getByRole('button',{name:'Close draft preview',exact:true}).click();assert.equal(await companion.count(),0);await page.getByRole('button',{name:'Restore draft preview',exact:true}).click();await companion.waitFor();await page.screenshot({path:path.join(root,'docs/qa/companion-preview-review.png'),fullPage:true});console.log('PASS companion preview beside main monitor, minimize, restore and close preserve controls');
 await page.getByRole('slider',{name:'Overlay width slider',exact:true}).fill('50');await page.getByRole('button',{name:'Apply changes',exact:true}).click();await saved(p=>p.finishing_json.layer_clips[0].width===50);await page.getByRole('button',{name:'Saved',exact:true}).waitFor();
 await seek(1500);const live=page.locator(`.preview-canvas video[data-preview-layer="${layer.id}"]`);await live.waitFor({state:'visible'});await page.waitForFunction(id=>{const v=document.querySelector(`video[data-preview-layer="${id}"]`);return v?.readyState>=1;},layer.id);assert(Math.abs(await live.evaluate(v=>v.currentTime)-.5)<.2);
 await page.locator(`[data-layer-id="${layer.id}"]`).focus();await page.keyboard.press('Control+d');p=await saved(p=>p.finishing_json.layer_clips.length===2);const duplicated=p.finishing_json.layer_clips[1];assert.equal(duplicated.kind,'video');assert.equal(duplicated.track,1);await page.keyboard.press('Control+z');await saved(p=>p.finishing_json.layer_clips.length===1);await page.keyboard.press('Control+y');await saved(p=>p.finishing_json.layer_clips.length===2);console.log('PASS video chooser, independent stack, seeked video preview, placement, duplication and Undo/Redo');
 await page.getByTitle('Return to scene controls',{exact:true}).click();await page.getByRole('tab',{name:'Audio',exact:true}).click();
 for(const name of ['Trim & listen','Level & fades','Voice cleanup & style','Background music','Final loudness'])await page.getByRole('heading',{name,exact:true}).waitFor();
 await page.getByLabel('Censor start seconds',{exact:true}).first().fill('0.5');await page.getByLabel('Censor end seconds',{exact:true}).first().fill('0.8');await page.getByRole('button',{name:'Add censor range',exact:true}).first().click();await saved(p=>p.scenes[0].voice_takes.find(t=>t.accepted).edit_json.censor?.length===1);await page.getByRole('button',{name:'Remove censor range 1',exact:true}).click();await saved(p=>!p.scenes[0].voice_takes.find(t=>t.accepted).edit_json.censor?.length);console.log('PASS narration censor range saves and removes');
 await page.getByRole('checkbox',{name:'Mute scene narration',exact:true}).check();await saved(p=>p.scenes[0].voice_takes.find(t=>t.accepted).edit_json.volume===0);await page.getByRole('checkbox',{name:'Mute scene narration',exact:true}).uncheck();await saved(p=>(p.scenes[0].voice_takes.find(t=>t.accepted).edit_json.volume??100)===100);
 await page.getByRole('button',{name:'Clear speech',exact:true}).click();await saved(p=>p.scenes[0].voice_takes.find(t=>t.accepted).edit_json.voice_fx==='clean');await page.getByRole('combobox',{name:'Audio preview speed',exact:true}).selectOption('1.25');await page.getByRole('checkbox',{name:'Listen to original audio',exact:true}).check();assert.equal(await page.getByRole('combobox',{name:'Audio preview speed',exact:true}).inputValue(),'1.25');
 await page.getByRole('button',{name:'Voice first',exact:true}).click();await saved(p=>p.finishing_json.music.volume===20&&p.finishing_json.music.duck===85);
 await page.getByRole('button',{name:'Duplicate audio clip',exact:true}).click();p=await saved(p=>p.finishing_json.audio_clips.length===2);const audioId=p.finishing_json.audio_clips[1].id;assert.equal(p.finishing_json.audio_clips[1].track,'A4');await page.getByRole('spinbutton',{name:'Timeline audio start seconds',exact:true}).fill('1.5');await saved(p=>p.finishing_json.audio_clips.find(c=>c.id===audioId).start_ms===1500);await page.getByRole('button',{name:'Soft fades',exact:true}).click();await saved(p=>p.finishing_json.audio_clips.find(c=>c.id===audioId).fade_in_ms===500);console.log('PASS styled audio groups, narration mute, cleanup preset, listening options, music preset, audio duplicate/position/fades');
 await page.getByRole('separator',{name:'Resize scene settings (double-click to reset)',exact:true}).focus();for(let i=0;i<9;i++)await page.keyboard.press('ArrowLeft');await page.getByRole('heading',{name:'Background music',exact:true}).scrollIntoViewIfNeeded();fs.mkdirSync(path.join(root,'docs/qa'),{recursive:true});await page.screenshot({path:path.join(root,'docs/qa/audio-review-dark.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.waitForFunction(()=>{const b=Array.from(document.querySelectorAll('button')).find(b=>b.textContent==='Voice first');return b&&getComputedStyle(b).backgroundColor==='rgb(255, 255, 255)';});const colors=await page.getByRole('button',{name:'Voice first',exact:true}).evaluate(e=>{const s=getComputedStyle(e);return {bg:s.backgroundColor,fg:s.color};});const lum=color=>{const rgb=color.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4;});return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722;};const a=lum(colors.bg),b=lum(colors.fg);assert((Math.max(a,b)+.05)/(Math.min(a,b)+.05)>4.5,'light audio action contrast');await page.screenshot({path:path.join(root,'docs/qa/audio-review-light.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');
 const cid=await page.getByRole('combobox',{name:'Select timeline audio clip',exact:true}).inputValue();const tc=page.locator('.scene-editor:not([hidden]) .timeline-audio-controls .audio-censor:visible');await tc.getByLabel('Censor start seconds',{exact:true}).fill('0.5');await tc.getByLabel('Censor end seconds',{exact:true}).fill('0.8');await tc.getByRole('button',{name:'Add censor range',exact:true}).click();await saved(p=>p.finishing_json.audio_clips.find(c=>c.id===cid).censor?.length===1);await page.getByRole('button',{name:'Undo timeline edit',exact:true}).click();await saved(p=>!p.finishing_json.audio_clips.find(c=>c.id===cid).censor?.length);await page.getByRole('button',{name:'Redo timeline edit',exact:true}).click();await saved(p=>p.finishing_json.audio_clips.find(c=>c.id===cid).censor?.length===1);console.log('PASS timeline censor range shares Undo/Redo history');
 await page.getByRole('button',{name:'Edit captions & titles',exact:true}).click();await page.getByRole('combobox',{name:'Caption 1 emoji',exact:true}).selectOption('fire');await saved(p=>p.scenes[0].font_json.caption_segments[0].emoji==='fire');await page.getByRole('combobox',{name:'Caption 1 emoji side',exact:true}).selectOption('left');await saved(p=>p.scenes[0].font_json.caption_segments[0].emoji_side==='left');await seek(1500);await page.locator('.caption-emoji-preview').waitFor({state:'visible'});
 await page.getByRole('tab',{name:'Effects',exact:true}).click();await page.locator('.fx-group').filter({hasText:'Finishing touches'}).locator('button').first().click();for(const label of ['Edge vignette','Cinema bars','Detail sharpening'])await page.getByRole('checkbox',{name:label,exact:true}).check();await saved(p=>p.scenes[0].look_json.vignette&&p.scenes[0].look_json.letterbox&&p.scenes[0].look_json.sharpen);await page.screenshot({path:path.join(root,'docs/qa/finishing-effects-review.png'),fullPage:true});console.log('PASS timed caption emoji and finishing effects save through their own sections');
 await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Script → Scenes…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Story tools'});await dialog.getByRole('checkbox',{name:'Prepare imported scenes',exact:true}).check();await dialog.getByRole('combobox',{name:'Script scene pictures',exact:true}).selectOption('pool');await dialog.getByRole('group',{name:'Script scene media choices',exact:true}).getByText('image1.png',{exact:true}).locator('input').check();await dialog.getByRole('combobox',{name:'Script image motion',exact:true}).selectOption('zoom_in');await dialog.getByRole('combobox',{name:'Script caption timing',exact:true}).selectOption('script');await dialog.getByRole('combobox',{name:'Script caption style',exact:true}).selectOption({label:'Arabic Tajawal box'});await dialog.getByRole('textbox',{name:'Script to split',exact:true}).fill('A calm mountain story begins here.\n\nأهلا بكم في هذه القصة الجديدة.');await dialog.getByRole('button',{name:'Preview scenes',exact:true}).click();await dialog.getByRole('textbox',{name:'Preview scene 1 narration',exact:true}).waitFor();await page.screenshot({path:path.join(root,'docs/qa/script-setup-review.png'),fullPage:true});await dialog.getByRole('button',{name:'Add 2 scenes',exact:true}).click();await dialog.waitFor({state:'detached'});await page.getByText(/2 scenes added with your selected setup/).first().waitFor();p=await read();const batch=p.scenes.slice(3);assert.equal(batch.length,2);assert.deepEqual(p.scenes.slice(0,3).map(s=>s.id),initialIds);assert(batch.every(s=>s.shots.length===1&&s.shots[0].asset_id===photo.id&&s.shots[0].motion_json.type==='zoom_in'&&s.font_json.caption_segments.length&&s.font_json.family==='Tajawal'&&s.voice_takes.length===0));
 await page.locator('.save-status').filter({hasText:'All changes saved'}).waitFor();await page.keyboard.press('Control+z');await saved(p=>p.scenes.length===3);await page.keyboard.press('Control+y');p=await saved(p=>p.scenes.length===5);assert.deepEqual(p.scenes.slice(3).map(s=>s.id),batch.map(s=>s.id));assert.deepEqual(p.scenes.slice(3).map(s=>s.font_json.caption_segments),batch.map(s=>s.font_json.caption_segments));assert.equal(p.finishing_json.layer_clips.length,2);console.log('PASS optional Script → Scenes prepares actual pictures, motion and caption boxes; batch Undo/Redo retains setup');
 await page.reload();await page.getByRole('button',{name:/Combined tools review Open project/}).click();await page.getByRole('button',{name:/Select scene 1:/}).click();await page.getByRole('button',{name:'Edit captions & titles',exact:true}).click();assert.equal(await page.getByRole('combobox',{name:'Caption 1 emoji',exact:true}).inputValue(),'fire');assert.equal(await page.getByRole('combobox',{name:'Caption 1 emoji side',exact:true}).inputValue(),'left');p=await read();assert(p.finishing_json.audio_clips.find(c=>c.id===cid).censor.length===1&&p.scenes[0].look_json.sharpen.amount===50);console.log('PASS caption emoji, censor ranges and finishing effects persist after reopening');

 await page.getByRole('button',{name:'Browse 322 emoji',exact:true}).click();await page.getByRole('searchbox',{name:'Search caption 1 emoji'}).fill('grinning face');await page.getByRole('button',{name:'Use Grinning face emoji',exact:true}).click();p=await saved(p=>p.scenes[0].font_json.caption_segments[0].emoji==='grinning-face');await page.screenshot({path:path.join(root,'docs/qa/caption-emoji-access-review.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='light');const cc=await page.getByRole('button',{name:'Close emoji browser',exact:true}).evaluate(el=>({bg:getComputedStyle(el).backgroundColor,fg:getComputedStyle(el).color}));assert((Math.max(lum(cc.bg),lum(cc.fg))+.05)/(Math.min(lum(cc.bg),lum(cc.fg))+.05)>4.5,'caption emoji action contrast');await page.screenshot({path:path.join(root,'docs/qa/caption-emoji-light-review.png'),fullPage:true});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.getByRole('button',{name:'Close emoji browser',exact:true}).click();
 await page.getByRole('tab',{name:'Effects',exact:true}).click();await page.getByRole('searchbox',{name:'Search effects'}).fill('sharpen');await page.getByRole('checkbox',{name:'Detail sharpening',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:/Colour grading/}).count(),0);await page.getByRole('button',{name:'Vignette · Bars · Sharpen',exact:true}).click();await page.getByRole('checkbox',{name:'Edge vignette',exact:true}).waitFor();assert.equal(await page.getByRole('searchbox',{name:'Search effects'}).inputValue(),'');
 await page.getByRole('button',{name:'Map route',exact:true}).click();await page.getByRole('switch',{name:'Map route',exact:true}).check();await saved(p=>!!p.scenes[0].look_json.route);await page.getByRole('button',{name:'Flight',exact:true}).click();await saved(p=>p.scenes[0].look_json.route.marker==='plane');await page.getByRole('button',{name:'Add stop',exact:true}).click();await saved(p=>p.scenes[0].look_json.route.points.length===4);await page.getByRole('spinbutton',{name:'Route stop 4 Left–right',exact:true}).fill('68');await saved(p=>p.scenes[0].look_json.route.points[3][0]===68);await page.getByRole('textbox',{name:'Label for stop 4',exact:true}).fill('Tampa');await page.getByRole('textbox',{name:'Label for stop 4',exact:true}).press('Tab');await saved(p=>p.scenes[0].look_json.route.labels[3]==='Tampa');
 await page.getByRole('button',{name:'Reverse journey',exact:true}).click();await saved(p=>p.scenes[0].look_json.route.labels[0]==='Tampa');await page.getByRole('button',{name:'Route stop 1',exact:true}).focus();await page.keyboard.press('Shift+ArrowRight');await saved(p=>p.scenes[0].look_json.route.points[0][0]===73);await page.getByRole('button',{name:'Route stop 1',exact:true}).focus();await page.keyboard.press('Delete');await saved(p=>p.scenes[0].look_json.route.points.length===3);await page.keyboard.press('Control+z');await saved(p=>p.scenes[0].look_json.route.points.length===4);await page.keyboard.press('Control+y');await saved(p=>p.scenes[0].look_json.route.points.length===3);await page.screenshot({path:path.join(root,'docs/qa/route-access-review.png'),fullPage:true});
 await page.getByRole('tab',{name:'Overlays',exact:true}).click();await page.getByRole('combobox',{name:'Add overlay from media',exact:true}).selectOption(photo.id);await saved(p=>p.scenes[0].overlays_json?.length===1);await page.getByRole('navigation',{name:'Overlay control shortcuts'}).getByRole('button',{name:'Timing & animation',exact:true}).click();assert.equal(await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')),'Overlay start seconds');await page.getByRole('navigation',{name:'Overlay control shortcuts'}).getByRole('button',{name:'Position & size',exact:true}).click();await page.screenshot({path:path.join(root,'docs/qa/overlay-access-review.png'),fullPage:true});assert.equal(await page.locator('.route-canvas').count(),0,'route handles belong to Effects only');const grid=await page.locator('.overlay-panel .panel-grid').evaluate(el=>{const a=el.children[0].getBoundingClientRect(),b=el.children[1].getBoundingClientRect();return {width:el.getBoundingClientRect().width,sameColumn:Math.abs(a.x-b.x)<2};});if(grid.width<=480)assert(grid.sameColumn,'narrow overlay panel uses readable single column');
 await page.reload();await page.getByRole('button',{name:/Combined tools review Open project/}).click();p=await read();assert.equal(p.scenes[0].font_json.caption_segments[0].emoji,'grinning-face');assert.equal(p.scenes[0].look_json.route.marker,'plane');assert.equal(p.scenes[0].look_json.route.points.length,3);console.log('PASS full emoji browser, searched and direct effect access, route presets/coordinates/reverse/keyboard/Undo/Redo, overlay shortcut focus and reopen');
 assert.deepEqual(errors,[]);console.log('PASS no browser errors or paid generation calls');
 }catch(e){if(browser){const page=browser.contexts()[0]?.pages()[0];if(page)await page.screenshot({path:path.join(data,'failure.png'),fullPage:true}).catch(()=>{});}console.error('Failure artifacts:',data);console.error(logs.slice(-1000));throw e;}finally{if(browser)await browser.close();if(server)server.kill();if(dev)dev.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
