import {JSDOM} from 'jsdom';import {build} from 'esbuild';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLTextAreaElement','Event','MouseEvent','CustomEvent'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
await build({entryPoints:['src/AudioCensor.tsx'],outdir:'node_modules/.cache/censor-test',bundle:true,platform:'node',format:'cjs',external:['react'],logLevel:'silent'});
const require=createRequire(import.meta.url),React=require('react'),{AudioCensor,wordMatches}=require('../node_modules/.cache/censor-test/AudioCensor.js');const {render,screen,fireEvent,cleanup}=await import('@testing-library/react');
const words=[['Hello,',200,500],['مرحبا',700,1000],['hello',1200,1400]];
assert.equal(wordMatches(words,'hello, مَرْحَبًا').length,3);assert.equal(wordMatches(words,'hell').length,0);assert.equal(wordMatches(words,'hello',300)[0].start_ms,460);
let rows=[];function Harness(){const [ranges,setRanges]=React.useState([]);return React.createElement(AudioCensor,{ranges,sourceMs:2000,words,onChange:r=>{rows=r;setRanges(r);}});}
render(React.createElement(Harness));fireEvent.change(screen.getByLabelText('Censor start seconds'),{target:{value:'.5'}});fireEvent.change(screen.getByLabelText('Censor end seconds'),{target:{value:'.8'}});fireEvent.click(screen.getByRole('button',{name:'Add censor range'}));assert.deepEqual(rows,[{start_ms:500,end_ms:800,mode:'bleep'}]);fireEvent.click(screen.getByRole('button',{name:'Add censor range'}));assert.equal(rows.length,1);assert(screen.getByRole('alert'));fireEvent.click(screen.getByRole('button',{name:'Remove censor range 1'}));assert.equal(rows.length,0);
fireEvent.change(screen.getByLabelText('Censored word list'),{target:{value:'hello'}});fireEvent.click(screen.getByRole('button',{name:'Review word matches'}));assert.equal(rows.length,0);fireEvent.click(screen.getByRole('button',{name:'Add reviewed matches'}));assert.equal(rows.length,2);cleanup();console.log('PASS source ranges, overlap rejection, exact English/Arabic word matching and review before apply');
