// Component interaction tests against an in-memory API fixture.
// These complement tests/integration/test_editor_mvp1.py; no real provider is called.
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost'});
for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLTextAreaElement','Event','MouseEvent','CustomEvent','KeyboardEvent','File','FormData']) Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
globalThis.requestAnimationFrame=cb=>setTimeout(()=>cb(Date.now()),0);globalThis.cancelAnimationFrame=id=>clearTimeout(id);
window.HTMLMediaElement.prototype.pause=function(){};
globalThis.confirm=()=>true;
globalThis.EventSource=class{addEventListener(){} close(){}};
await build({entryPoints:['src/App.tsx'],outfile:'node_modules/.cache/editor-test.cjs',bundle:true,platform:'node',format:'cjs',external:['react','react-dom'],logLevel:'silent'});
const require=createRequire(import.meta.url);
const React=require('react');
const {default:App}=require('../node_modules/.cache/editor-test.cjs');
const {render,screen,within,waitFor,cleanup,act}=await import('@testing-library/react');
const {default:userEvent}=await import('@testing-library/user-event');
const user=userEvent.setup();
const fixture=JSON.parse(readFileSync('../tests/ui-project-fixture.json','utf8'));
let project=structuredClone(fixture);
let failNextPatch=false;
let requests=[];
let next=10;
let profiles=[];
let healthBuild="workspace-2.5";
let failLocal=true;
let closeReady=true;
const clone=x=>structuredClone(x);
globalThis.fetch=async(path,init={})=>{
 const method=init.method||'GET'; const body=typeof init.body==='string'?JSON.parse(init.body):init.body;
 requests.push({path,method,body});
 let result;
 if(path==='/api/health')result={status:'ok',build:healthBuild};
 else if(path==='/api/close-status')result={ready:closeReady};
 else if(path==='/api/projects'&&method==='GET') result=[project];
 else if(path===`/api/projects/${project.id}`&&method==='GET') result=project;
 else if(path===`/api/projects/${project.id}`&&method==='PATCH'){Object.assign(project,body); result=project;}
 else if(path===`/api/projects/${project.id}`&&method==='DELETE')result={ok:true};
 else if(path==='/api/providers'&&method==='GET') result=profiles;
 else if(path==='/api/providers'&&method==='POST'){const p={...body,id:'provider-'+body.name,configured:true,masked_key:'masked'};profiles=profiles.filter(v=>v.name!==p.name).concat(p);result=p;}
 else if(path==='/api/local-speech/kokoro/connect') {if(failLocal){failLocal=false;return {ok:false,status:503,json:async()=>({detail:'Engine is not running.'})};}const profile={id:'provider-kokoro',name:'kokoro',capability:'speech',base_url:'http://127.0.0.1:8880'};profiles.push(profile);result={profile,voices:['af_heart'],message:'Service connected.'};}
 else if(path.endsWith('/voices'))result={voices:['af_heart','default']};
 else if(path.endsWith('/image-history'))result=[];
 else if(path.endsWith('/generate-image'))result={id:'generated-image'};
 else if(path.endsWith('/scene-order')) {project.scenes=body.scene_ids.map(id=>project.scenes.find(s=>s.id===id));result={ok:true};}
 else if(path===`/api/projects/${project.id}/scenes`&&method==='POST') {
  const s=clone(fixture.scenes[1]);s.id='new-'+next++;s.title='New scene';project.scenes.push(s);result=s;
 }
 else if(path.startsWith('/api/scenes/shots/')&&method==='PATCH') {const id=path.split('/').at(-1);const shot=project.scenes.flatMap(s=>s.shots).find(s=>s.id===id);Object.assign(shot,body);if(body.motion)shot.motion_json=body.motion;result=shot;}
 else if(path.startsWith('/api/scenes/')&&method==='PATCH') {
  await new Promise(r=>setTimeout(r,25));
  if(failNextPatch){failNextPatch=false;return {ok:false,status:503,statusText:'Unavailable',json:async()=>({detail:'Save failed for test'})};}
  const s=project.scenes.find(s=>s.id===path.split('/').at(-1));
  const {font,...fields}=body;Object.assign(s,fields);if(body.transition_in)s.transition_in_json=body.transition_in;if(font)Object.assign(s.font_json,font);s.is_stale=true;result=s;
 }
 else if(path.startsWith('/api/scenes/')&&method==='DELETE'){project.scenes=project.scenes.filter(s=>s.id!==path.split('/').at(-1));result={ok:true};}
 else throw Error(`Unhandled test API: ${method} ${path}`);
 return {ok:true,status:200,json:async()=>clone(result)};
};
let passed=0;
const check=(name,condition=true)=>{assert.ok(condition,name);console.log('PASS '+name);passed++;};
const visibleEditor=()=>within(screen.getByRole('region',{name:/Edit /}));
const saved=()=>waitFor(()=>assert.equal(screen.getByRole('status').textContent,'All changes saved'));
try{
 render(React.createElement(App));
 await screen.findByRole('button',{name:/Editor MVP1 regression Open project/});
 await user.type(screen.getByRole('textbox',{name:'Search projects'}),'missing project');
 check('project search filters saved projects',!!screen.getByText('No matching projects.'));
 await user.clear(screen.getByRole('textbox',{name:'Search projects'}));
 globalThis.confirm=()=>false;
 await user.click(screen.getByRole('button',{name:/Delete project Editor MVP1/}));
 check('cancelling project deletion makes no delete request',!requests.some(r=>r.method==='DELETE'));
 globalThis.confirm=()=>true;
 await user.click(await screen.findByRole('button',{name:/Editor MVP1 regression Open project/}));
 await screen.findByRole('region',{name:/Edit /});
 check('project opens and only selected scene is visible',screen.getAllByRole('region',{name:/Edit /}).length===1);
 const firstId=project.scenes[0].id, secondId=project.scenes[1].id;
 check('timeline automatically includes every scene',screen.getAllByRole('button',{name:/Storyboard scene/}).length===project.scenes.length);
 check('movie preview waits for a completed export',screen.getByRole('button',{name:'Preview last export'}).disabled);
 await user.click(screen.getByRole('button',{name:'Fit timeline'}));
 check('fit timeline sets an allowed zoom',Number(screen.getByRole('slider',{name:'Timeline zoom'}).value)>=12);
 check('left library has no duplicate Effects tab',!screen.queryByRole('button',{name:'Effects',exact:true})&&!!screen.getByRole('tab',{name:'Effects',exact:true}));
 check('transport has one play toggle and icon scene navigation',!screen.queryByRole('button',{name:'Pause full video'})&&!screen.queryByRole('button',{name:'Prev',exact:true})&&!screen.queryByRole('button',{name:'Next',exact:true})&&!!screen.getByRole('button',{name:'Previous scene'})&&!!screen.getByRole('button',{name:'Next scene'}));
 check('render full video sits with timeline tools, not playback',!within(screen.getByRole('group',{name:'Playback'})).queryByRole('button',{name:/Render full video/})&&!!screen.getByRole('button',{name:/Render full video/}));
 const tc=()=>screen.getByLabelText('Timeline timecode').textContent;
 await user.keyboard('{End}');const atEnd=tc();
 await user.keyboard('{Home}');
 check('End and Home shortcuts move the playhead',atEnd!=='00:00:00:00'&&tc()==='00:00:00:00');
 await user.keyboard('{Shift>}{ArrowRight}{/Shift}');
 check('Shift+Right jumps to the next scene start',tc()!=='00:00:00:00');
 await user.keyboard('{Home}');
 const script=visibleEditor().getAllByRole('textbox')[0];script.focus();
 await user.keyboard('{End}');
 check('shortcuts are ignored while typing in a text field',tc()==='00:00:00:00');
 script.blur();
 check('first clip has no incoming transition',screen.getByRole('combobox',{name:'Incoming transition'}).disabled);
 await user.click(screen.getByRole('button',{name:'Move timeline part later'}));
 await waitFor(()=>assert.equal(project.scenes[1].id,firstId));
 check('timeline reordering persists the export sequence');
 await user.click(screen.getByRole('button',{name:'Move timeline part earlier'}));
 await waitFor(()=>assert.equal(project.scenes[0].id,firstId));

 await user.clear(visibleEditor().getByRole('textbox',{name:'Narration script'}));
 await user.type(visibleEditor().getByRole('textbox',{name:'Narration script'}),'An edited narration.');
 await user.click(screen.getByRole('button',{name:'Select scene 2: Part-2'}));
 await saved();
 check('switching scenes flushes the draft to the correct scene',project.scenes.find(s=>s.id===firstId).spoken_text==='An edited narration.'&&project.scenes.find(s=>s.id===secondId).spoken_text==='');
 await user.click(screen.getByRole('button',{name:'Select scene 1: Part-1'}));
 check('returning preserves edited narration',visibleEditor().getByRole('textbox',{name:'Narration script'}).value==='An edited narration.');
 await user.click(screen.getByRole('tab',{name:'Text',exact:true}));
 check('existing captions preserved when narration changes',visibleEditor().getByRole('textbox',{name:'On-screen captions'}).value===fixture.scenes[0].subtitle_text);
 await user.clear(visibleEditor().getByRole('textbox',{name:'On-screen captions'}));
 await user.type(visibleEditor().getByRole('textbox',{name:'On-screen captions'}),'مرحبا — Altair 8800');
 await user.click(screen.getByRole('tab',{name:'Media',exact:true}));
 await saved();
 await user.selectOptions(screen.getByRole('combobox',{name:'Frame fit'}),'contain');await saved();
 check('fit setting reaches the main image',visibleEditor().getByRole('img',{name:/Source media/}).style.objectFit==='contain');
 await waitFor(()=>assert.ok(!screen.getByRole('combobox',{name:'Frame fit'}).disabled));
 await user.selectOptions(screen.getByRole('combobox',{name:'Frame fit'}),'cover');
 await waitFor(()=>assert.equal(visibleEditor().getByRole('img',{name:/Source media/}).style.objectFit,'cover'));await saved();
 check('fill setting reaches the main image',visibleEditor().getByRole('img',{name:/Source media/}).style.objectFit==='cover');
 await user.click(screen.getByRole('tab',{name:'Motion',exact:true}));
 check('independent Arabic caption editing',project.scenes.find(s=>s.id===firstId).subtitle_text==='مرحبا — Altair 8800'&&project.scenes.find(s=>s.id===firstId).spoken_text==='An edited narration.');
 await user.click(screen.getByRole('button',{name:'Pan left',exact:true}));await saved();
 check('motion selection updates the selected media',project.scenes.find(s=>s.id===firstId).shots[0].motion_json.type==='pan_left');
 await user.click(screen.getByRole('tab',{name:'Effects',exact:true}));
 await user.type(screen.getByRole('textbox',{name:'Search effects'}),'warm');
 check('effect search narrows visible choices',screen.getAllByRole('button',{name:'Warm',exact:true}).length===1&&!screen.queryByRole('button',{name:'Cool',exact:true}));
 await user.click(screen.getByRole('button',{name:'Warm',exact:true}));await saved();
 check('effect selection persists',project.scenes.find(s=>s.id===firstId).effect_preset==='warm');
 check('effect appears on main preview',visibleEditor().getByRole('img',{name:/Source media/}).style.filter.includes('saturate'));
 await user.click(screen.getByRole('tab',{name:'Text',exact:true}));
 await user.selectOptions(screen.getByLabelText('Family'),'Noto Sans Arabic');await saved();
 check('font selection retains other font settings',project.scenes.find(s=>s.id===firstId).font_json.family==='Noto Sans Arabic'&&project.scenes.find(s=>s.id===firstId).font_json.size===40);
 await user.click(screen.getByRole('checkbox',{name:'Synchronized keystrokes'}));await saved();
 check('typewriter sound settings save independently',project.scenes.find(s=>s.id===firstId).font_json.typewriter_sound===true);
 await user.click(screen.getByRole('button',{name:'Copy narration to captions'}));await saved();
 await user.click(screen.getByRole('button',{name:'Slow',exact:true}));await saved();
 check('slow typing preset saves a longer reveal',project.scenes.find(s=>s.id===firstId).font_json.typewriter_duration_ms>3000);
 await user.click(screen.getByRole('button',{name:'Extend scene to fit typing + 1s hold'}));await saved();
 check('extend scene preserves requested typing duration',project.scenes.find(s=>s.id===firstId).requested_duration_ms>project.scenes.find(s=>s.id===firstId).font_json.typewriter_duration_ms);
 await user.click(screen.getByRole('button',{name:'Add text overlay'}));await saved();
 check('text overlay appears in editor canvas',visibleEditor().getByText('Your title',{selector:'.canvas-text-layer'}));
 const layerText=visibleEditor().getByRole('textbox',{name:'Layer 1 text'});
 await user.clear(layerText);await user.type(layerText,'A chapter title');await user.tab();await saved();
 check('overlay text persists independently of captions',project.scenes.find(s=>s.id===firstId).font_json.layers[0].text==='A chapter title');
 await user.click(screen.getByRole('checkbox',{name:'Captions enabled'}));await saved();
 await user.click(screen.getByRole('checkbox',{name:/Typewriter reveal/}));await saved();
 check('typewriter enables captions without overwriting their text',project.scenes.find(s=>s.id===firstId).font_json.captions_enabled&&project.scenes.find(s=>s.id===firstId).font_json.typewriter&&project.scenes.find(s=>s.id===firstId).subtitle_text==='An edited narration.');
 await user.click(screen.getByRole('button',{name:'Edit captions & titles'}));
 const reopened=visibleEditor().getByRole('textbox',{name:'Layer 1 text'});
 await user.clear(reopened);await user.type(reopened,'Revised title');await saved();
 check('title saves while focused and remains editable',document.activeElement===reopened&&project.scenes.find(s=>s.id===firstId).font_json.layers[0].text==='Revised title');
 await user.click(screen.getByRole('tab',{name:'Audio',exact:true}));
 await user.click(screen.getByRole('button',{name:'Edit captions & titles'}));
 check('title can be reopened without deleting the scene',visibleEditor().getByRole('textbox',{name:'Layer 1 text'}).value==='Revised title');
 check('explicit copy narration action',project.scenes.find(s=>s.id===firstId).subtitle_text==='An edited narration.');
 await user.click(screen.getByRole('button',{name:'Move scene down'}));await waitFor(()=>assert.equal(project.scenes[1].id,firstId));
 check('reordering retains selection',screen.getByRole('button',{name:'Select scene 2: Part-1'}).getAttribute('aria-current')==='true');
 await user.click(screen.getByRole('button',{name:'Collapse scene list'}));
 check('scene list collapses',!screen.queryByRole('button',{name:'Select scene 2: Part-1'}));
 await user.click(screen.getByRole('button',{name:'Expand scene list'}));
 await user.click(screen.getByRole('button',{name:'Add scene',exact:true}));await waitFor(()=>assert.equal(project.scenes.length,4));
 check('added scene is selected',screen.getByRole('region',{name:'Edit New scene'}));
 check('empty scene blocks rendering',screen.getByRole('button',{name:'Render scene'}).disabled);
 await user.click(screen.getByRole('button',{name:'Select scene 2: Part-1'}));
 failNextPatch=true;
 await user.clear(visibleEditor().getByRole('textbox',{name:'Narration script'}));
 await user.type(visibleEditor().getByRole('textbox',{name:'Narration script'}),'Recoverable draft');
 await waitFor(()=>assert.equal(screen.getByRole('status').textContent,'Save failed'),{timeout:2500});
 check('save failure keeps the draft and blocks export',visibleEditor().getByRole('textbox',{name:'Narration script'}).value==='Recoverable draft'&&screen.getByRole('button',{name:'Export video'}).disabled);
 await user.click(screen.getByRole('button',{name:'Retry text save / dismiss'}));await saved();
 check('failed save can be retried',project.scenes.find(s=>s.id===firstId).spoken_text==='Recoverable draft');
 await user.clear(screen.getByRole('textbox',{name:'Project name',exact:true}));
 await user.type(screen.getByRole('textbox',{name:'Project name',exact:true}),'Renamed project');
 await user.tab();await saved();
 check('project title saves with accurate status',project.title==='Renamed project');
 await user.type(visibleEditor().getByRole('textbox',{name:'Narration script'}),' before exit');
 let canClose;
 await act(async()=>{canClose=await window.__sceneForgePrepareClose();});
 check('desktop close flushes focused narration before exiting',canClose&&project.scenes.find(s=>s.id===firstId).spoken_text.endsWith(' before exit'));
 await user.type(visibleEditor().getByRole('textbox',{name:'Narration script'}),' keep draft');
 failNextPatch=true;
 await act(async()=>{canClose=await window.__sceneForgePrepareClose();});
 check('desktop close refuses failed save and preserves draft',!canClose&&visibleEditor().getByRole('textbox',{name:'Narration script'}).value.endsWith(' keep draft'));
 await act(async()=>{canClose=await window.__sceneForgePrepareClose();});
 check('desktop close can retry failed save',canClose);
 closeReady=false;
 await act(async()=>{canClose=await window.__sceneForgePrepareClose();});
 check('desktop close refuses active backend render',!canClose);
 closeReady=true;
 await user.selectOptions(screen.getByRole('combobox',{name:'Project aspect ratio'}),'9:16');await saved();
 check('project aspect selection saves',project.aspect==='9:16');
 await user.click(screen.getByRole('button',{name:'Provider settings',exact:true}));
 check('existing provider settings still accessible',screen.getByRole('heading',{name:'Settings — Providers'}));
 await user.selectOptions(screen.getByRole('combobox',{name:'Provider',exact:true}),'gemini');
 await user.type(screen.getByRole('textbox',{name:'Provider model'}),'-custom');
 await user.type(screen.getByLabelText('Provider API key'),'fixture-key');
 await user.click(screen.getByRole('button',{name:'Save provider'}));await screen.findByText('Provider saved.');
 check('Gemini profile saves selected provider and model',profiles.some(p=>p.name==='gemini'&&p.model.endsWith('-custom')));
 check('image providers exclude local speech components',!within(screen.getByRole('combobox',{name:'Provider',exact:true})).queryByText(/Kokoro/));
 await user.click(screen.getByRole('button',{name:'Close',exact:true}));
 await user.click(screen.getByRole('tab',{name:'Audio',exact:true}));
 check('robotic narration is not selected by default',screen.getByRole('combobox',{name:'Narration engine'}).value==='unselected');
 await user.click(screen.getByRole('button',{name:'Connect Kokoro',exact:true}));
 await screen.findByText('Engine is not running.');
 check('unavailable engine does not silently select robotic fallback',screen.getByRole('combobox',{name:'Narration engine'}).value==='unselected');
 await user.click(screen.getByRole('button',{name:'Connect Kokoro',exact:true}));
 await waitFor(()=>assert.equal(screen.getByRole('combobox',{name:'Narration voice'}).value,'af_heart'));
 check('Kokoro connects and selects a compatible voice',screen.getByRole('combobox',{name:'Narration language'}).value==='en');
 await user.click(screen.getByRole('tab',{name:'Media',exact:true}));
 await user.click(screen.getByRole('button',{name:'Generate image',exact:true}));
 await waitFor(()=>assert.equal(screen.getByRole('combobox',{name:'Image provider'}).value,'provider-gemini'));
 await user.selectOptions(screen.getByRole('combobox',{name:'Image composition'}),'1536x1024');
 await user.type(screen.getByPlaceholderText(/Describe your subject/),'A green landscape');
 await user.click(within(screen.getByRole('dialog')).getByRole('button',{name:'Generate image'}));
 await screen.findByRole('button',{name:'Use this image'});
 check('image studio sends chosen provider and composition',requests.some(r=>r.path.endsWith('/generate-image')&&r.body.provider_id==='provider-gemini'&&r.body.size==='1536x1024'));
 await user.click(screen.getByRole('button',{name:'Close',exact:true}));
 cleanup();
 render(React.createElement(App));
 await user.click(await screen.findByRole('button',{name:/Renamed project Open project/}));
 await user.click(screen.getByRole('button',{name:'Select scene 2: Part-1'}));
 check('reopening restores persisted text',visibleEditor().getByRole('textbox',{name:'Narration script'}).value==='Recoverable draft before exit keep draft');
 await user.click(screen.getByRole('button',{name:'SceneForge'}));
 await user.click(await screen.findByRole('button',{name:'Delete project Renamed project'}));
 await screen.findByText('Your saved projects will appear here.');
 check('confirmed deletion removes the project card',requests.some(r=>r.method==='DELETE'&&r.path===`/api/projects/${project.id}`));
 cleanup();healthBuild="old-backend";render(React.createElement(App));
 await screen.findByText(/Backend update required:/);
 check('mixed frontend and backend versions show a recovery notice');
 console.log(`${passed} component checks passed (mock API, not browser visual QA).`);
}finally{cleanup();}
