import {JSDOM} from 'jsdom';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLTextAreaElement','Event','KeyboardEvent'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
await build({entryPoints:['src/TitleDesigner.tsx','src/LocalAISetup.tsx'],outdir:'node_modules/.cache/friendly-test',bundle:true,platform:'node',format:'cjs',external:['react','react-dom'],logLevel:'silent'});
const require=createRequire(import.meta.url),React=require('react');
const {TitleDesigner}=require('../node_modules/.cache/friendly-test/TitleDesigner.js');
const {LocalAISetup}=require('../node_modules/.cache/friendly-test/LocalAISetup.js');
const {render,screen,fireEvent,cleanup,waitFor,act}=await import('@testing-library/react');
let oldClose=0,newClose=0;
const props={width:1920,height:1080,busy:false,onCreate:()=>{},onClose:()=>oldClose++};
const rendered=render(React.createElement(TitleDesigner,props));
const text=screen.getByLabelText('Title card text');
fireEvent.change(text,{target:{value:'Stable title · مرحبا'}});
const font=screen.getByRole('combobox',{name:'Title card font'});
assert.equal(font.options.length,19);
font.focus();
rendered.rerender(React.createElement(TitleDesigner,{...props,onClose:()=>newClose++}));
assert.equal(document.activeElement,font,'A parent update must not steal focus or scroll back to the title');
assert.equal(text.value,'Stable title · مرحبا');
rendered.rerender(React.createElement(TitleDesigner,{...props,busy:true,onClose:()=>newClose++}));
fireEvent.keyDown(document,{key:'Escape'});assert.equal(newClose,0);
rendered.rerender(React.createElement(TitleDesigner,{...props,onClose:()=>newClose++}));
fireEvent.keyDown(document,{key:'Escape'});assert.equal(newClose,1);assert.equal(oldClose,0);
cleanup();console.log('PASS parent updates retain title focus/text, busy Escape guard, latest close callback, 19 real font choices');
let installBody,ready=0;
const state={status:'idle',completed:0,total:0,current:'',log:[],error:'',supported:true,settings:{autostart:true,components:[],gpu:false}};
globalThis.fetch=async(url,options={})=>{
 if(options.method==='POST'){installBody=JSON.parse(options.body);Object.assign(state,{status:'done',completed:3,total:3});return {ok:true,json:async()=>({started:true})};}
 return {ok:true,json:async()=>structuredClone(state)};
};
render(React.createElement(LocalAISetup,{onReady:()=>ready++}));
await waitFor(()=>assert(screen.getByRole('button',{name:'Install selected AI'}).disabled));
fireEvent.click(screen.getByLabelText('Accept local AI component terms'));
await waitFor(()=>assert(!screen.getByRole('button',{name:'Install selected AI'}).disabled));
fireEvent.click(screen.getByRole('button',{name:'Install selected AI'}));
await waitFor(()=>assert.deepEqual(installBody,{components:['whisper','stable_diffusion','chatterbox'],accept_terms:true,gpu:false}));
await waitFor(()=>assert.equal(screen.getByRole('progressbar').value,3));
cleanup();state.supported=false;state.status='idle';state.total=0;
render(React.createElement(LocalAISetup,{}));
fireEvent.click(screen.getByLabelText('Accept local AI component terms'));
await waitFor(()=>assert(screen.getByRole('button',{name:'Install selected AI'}).disabled));
cleanup();console.log('PASS installer terms gate, selected components, truthful completed progress and unsupported-platform guard; mocked installation only');
