// Exercise delayed saves and retry without a provider or production build.
import {JSDOM} from 'jsdom';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});
for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','HTMLTextAreaElement','Event','MouseEvent','CustomEvent','KeyboardEvent'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
await build({entryPoints:['src/TimelineLayers.tsx','src/SpeedControls.tsx'],outdir:'node_modules/.cache/inspector-test',bundle:true,platform:'node',format:'cjs',external:['react','react-dom'],logLevel:'silent'});
const require=createRequire(import.meta.url),React=require('react');
const {LayerInspector}=require('../node_modules/.cache/inspector-test/TimelineLayers.js');
const {SpeedControls}=require('../node_modules/.cache/inspector-test/SpeedControls.js');
const {render,screen,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');
const clip={id:'test',kind:'text',text:'Title',start_ms:0,duration_ms:3000,track:0,x:50,y:50,width:50,rotation:0,opacity:100,size:40};
let finish,calls=0,fail=false;
function Harness(){const [saved,setSaved]=React.useState(clip);return React.createElement(LayerInspector,{clip:saved,project:{id:'test',width:1920,height:1080,finishing_json:{layer_clips:[saved]}},length:10000,onClose:()=>{},actions:{disabled:false,onChange:async clips=>{calls++;await new Promise(resolve=>finish=resolve);if(fail)return false;setSaved(clips[0]);return true;}}});}
render(React.createElement(Harness));
assert(screen.getByRole('button',{name:'Saved',exact:true}).disabled);
fireEvent.change(screen.getByLabelText('Overlay text'),{target:{value:'Edited title'}});
fireEvent.click(screen.getByRole('button',{name:'Apply changes',exact:true}));
await waitFor(()=>assert.equal(calls,1));
assert(screen.getByRole('button',{name:'Saving…',exact:true}).disabled);
await act(async()=>finish());
await waitFor(()=>assert(screen.getByRole('button',{name:'Saved',exact:true}).disabled));
assert(screen.getByText('All changes saved.'));
fireEvent.change(screen.getByLabelText('Overlay text'),{target:{value:'Retry title'}});
assert(!screen.getByRole('button',{name:'Apply changes',exact:true}).disabled);
fail=true;fireEvent.click(screen.getByRole('button',{name:'Apply changes',exact:true}));
await waitFor(()=>assert.equal(calls,2));await act(async()=>finish());
assert(!screen.getByRole('button',{name:'Retry changes',exact:true}).disabled);
assert.equal(screen.getByLabelText('Overlay text').value,'Retry title');
fail=false;fireEvent.click(screen.getByRole('button',{name:'Retry changes',exact:true}));
await waitFor(()=>assert.equal(calls,3));await act(async()=>finish());
await waitFor(()=>assert(screen.getByRole('button',{name:'Saved',exact:true}).disabled));
cleanup();
let speed;
render(React.createElement(SpeedControls,{shot:{id:'shot',speed_json:{}},disabled:false,save:value=>speed=value}));
for(const name of ['Playback speed','Speed ramp','Slow motion','Freeze frame'])assert(screen.getByRole('heading',{name,exact:true}));
assert.equal(screen.getAllByRole('radio').length,7);
fireEvent.click(screen.getByRole('radio',{name:'Custom curve',exact:true}));
assert.equal(speed.ramp,'curve');assert.equal(screen.getAllByRole('slider').length,4);
fireEvent.click(screen.getByLabelText('Smooth slow motion'));assert.equal(speed.smooth,true);
fireEvent.change(screen.getByLabelText('Freeze hold seconds'),{target:{value:'2'}});assert.equal(speed.freeze_ms,2000);
fireEvent.click(screen.getByRole('button',{name:'Reset speed',exact:true}));assert.equal(speed.speed,1);assert.equal(speed.ramp,'none');assert.equal(speed.freeze_ms,0);
cleanup();console.log('PASS overlay saving/saved/edit/retry states and all grouped speed controls');
