import {JSDOM} from 'jsdom';import {build} from 'esbuild';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','Event','MouseEvent','CustomEvent','KeyboardEvent'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
await build({entryPoints:['src/EffectsPanels.tsx','src/RouteArtwork.tsx','src/StorySceneSetup.tsx','src/ScriptStoryboard.tsx','src/timeline/sceneSelection.ts'],outdir:'node_modules/.cache/owner-fixes',bundle:true,platform:'node',format:'cjs',external:['react'],logLevel:'silent'});
const require=createRequire(import.meta.url),React=require('react');const {render,screen,fireEvent,cleanup}=await import('@testing-library/react');
const {SceneEffectsPanel}=require('../node_modules/.cache/owner-fixes/EffectsPanels.js'),{RouteDestination}=require('../node_modules/.cache/owner-fixes/RouteArtwork.js'),{StorySceneSetup}=require('../node_modules/.cache/owner-fixes/StorySceneSetup.js'),{ScriptStoryboard}=require('../node_modules/.cache/owner-fixes/ScriptStoryboard.js'),{reorderSceneSelection,sceneShotSegments,scenePictureTiles,scenesInBox}=require('../node_modules/.cache/owner-fixes/timeline/sceneSelection.js');
const route={points:[[12,94],[50,45],[89,3]],labels:['Spain','Rome',''],color:'#E8413C',width:8,style:'solid',pins:true,start_ms:0,draw_ms:1000,marker:'none'};let draft=route;
function Editor(){const [r,set]=React.useState(route);return React.createElement(SceneEffectsPanel,{scene:{id:'s',shots:[],look_json:{route:r}},disabled:false,onDraft:look=>{draft=look.route;set(draft);}});}
render(React.createElement(Editor));fireEvent.change(screen.getByLabelText('Label for stop 3'),{target:{value:'London'}});assert.equal(draft.labels[2],'London','Last keystroke must be in draft immediately');fireEvent.click(screen.getByRole('button',{name:'Reverse journey'}));assert.deepEqual(draft.labels,['London','Rome','Spain']);assert.equal(screen.getByLabelText('Label for stop 1').value,'London');fireEvent.click(screen.getByRole('button',{name:'Add stop',exact:true}));assert.deepEqual(draft.labels,['London','Rome','Spain','']);cleanup();
for(const marker of ['none','dot','plane']){render(React.createElement(RouteDestination,{route:{...route,labels:['Spain','Rome','London'],marker},aspect:16/9}));for(const label of ['Spain','Rome','London'])assert(screen.getByText(label));cleanup();}
const options={pictures:'none',mediaIds:[],imageProviderId:'',voiceEngine:'paid',voice:'voice',language:'auto',captions:'keep',style:'',motion:'static',render:false,seconds:4};let changed;
render(React.createElement(StorySceneSetup,{options,onChange:o=>changed=o,assets:[],providers:[{id:'paid',capability:'speech',name:'elevenlabs'}],voices:[{id:'voice',name:'Voice'}],blocked:false,whisperReady:false,onEngine:()=>{}}));assert.equal(screen.getByLabelText('Script image motion').options.length,16);assert([...screen.getByLabelText('Script narration engine').options].some(o=>o.text.includes('ElevenLabs')));fireEvent.click(screen.getByLabelText('Allow paid ElevenLabs narration for this batch'));assert.equal(changed.paidNarrationConfirmed,true);cleanup();
render(React.createElement(ScriptStoryboard,{scenes:[{title:'One',spoken_text:'Welcome'},{title:'Two',spoken_text:'أهلا'}],options,prepare:false,assets:[],project:{aspect:'16:9',width:1920,height:1080,default_font_json:{}}}));fireEvent.click(screen.getByRole('button',{name:'Review script scene 2'}));assert(screen.getByRole('img',{name:'Scene 2 layout sample: Two'}));assert(screen.getByText('أهلا'));cleanup();
const ids=['a','b','c','d','e'];assert.deepEqual(reorderSceneSelection(ids,'b',['b','c'],'e',true),['a','d','e','b','c']);assert.deepEqual(reorderSceneSelection(ids,'d',['b','d'],'a'),['b','d','a','c','e']);assert.equal(reorderSceneSelection(ids,'b',['b','c'],'c'),ids);assert.deepEqual(reorderSceneSelection(ids,'a',['b','c'],'e',true),['b','c','d','e','a']);
const scene={shots:[{id:'ignored',is_selected:false,duration_ms:9000},{id:'one',is_selected:true,duration_ms:1000,asset:{type:'image'}},{id:'two',is_selected:true,duration_ms:2000,asset:{type:'video',duration_ms:8000}}],look_json:{}};assert.deepEqual(sceneShotSegments(scene,3000).map(x=>[x.shot.id,x.start,x.duration]),[['one',0,1000],['two',1000,2000]]);
assert.equal(scenePictureTiles({...scene,look_json:{layout:{type:'split2'}}},3000).length,2);assert.equal(scenePictureTiles({...scene,look_json:{layout:{type:'split2'}}},3000)[1].duration,1500);
const hitBoxes=[{id:'one',box:{x:20,y:10,width:40,height:30}},{id:'one',box:{x:20,y:50,width:40,height:10}},{id:'two',box:{x:65,y:10,width:40,height:30}},{id:'three',box:{x:110,y:10,width:40,height:30}}];
assert.deepEqual(scenesInBox({x:10,y:5,width:95,height:60},hitBoxes),['one','two']);
assert.deepEqual(scenesInBox({x:10,y:5,width:2,height:2},hitBoxes),[]);
assert.deepEqual(scenesInBox({x:105,y:5,width:5,height:40},hitBoxes),[]);
console.log('PASS mouse-box intersection, duplicate linked-track hits and tiny/edge gesture guards');
console.log('PASS immediate route labels, Reverse/Add, completed-route labels, 16 motions, explicit ElevenLabs choice, storyboard scene switching, grouped scene reorder and selected-shot boundaries');

render(React.createElement(StorySceneSetup,{options:{...options,voiceEngine:'none'},onChange:()=>{},assets:[],providers:[],voices:[],blocked:false,whisperReady:false,onEngine:()=>{}}));const engines=[...screen.getByLabelText('Script narration engine').options];for(const name of ['kokoro','chatterbox','ElevenLabs'])assert(engines.some(o=>o.text.includes(name)&&o.disabled));cleanup();console.log('PASS all supported narration engines remain discoverable when unconfigured');
