import {JSDOM} from 'jsdom';import {build} from 'esbuild';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const dom=new JSDOM('<html><body></body></html>',{url:'http://localhost'});for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','Event','MouseEvent','CustomEvent'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let calls=[],fail=false;globalThis.__testProviderApi={upsertProvider:async(...args)=>{calls.push(args);if(fail)throw Error('Credential store unavailable');}};
await build({entryPoints:['src/ProviderConnection.tsx'],outfile:'node_modules/.cache/provider-connections.cjs',bundle:true,platform:'node',format:'cjs',external:['react'],logLevel:'silent',plugins:[{name:'fake-provider-API',setup(b){b.onResolve({filter:/^\.\/api$/},()=>({path:'stub',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const api=globalThis.__testProviderApi;',loader:'js'}));}}]});
const require=createRequire(import.meta.url),React=require('react'),{ProviderConnection}=require('../node_modules/.cache/provider-connections.cjs');const {render,screen,fireEvent,waitFor,cleanup,act}=await import('@testing-library/react');let saved=0;
render(React.createElement(ProviderConnection,{name:'elevenlabs',onSaved:async()=>saved++}));const detail=document.querySelector('details');detail.open=true;assert.equal(calls.length,0);assert.equal(screen.getByLabelText('ElevenLabs API key').type,'password');assert(screen.getByRole('button',{name:'Save ElevenLabs provider'}).disabled);
fireEvent.change(screen.getByLabelText('ElevenLabs API key'),{target:{value:'TEST-ONLY-NOT-A-REAL-KEY'}});fireEvent.click(screen.getByRole('button',{name:'Save ElevenLabs provider'}));await waitFor(()=>assert.equal(saved,1));assert.deepEqual(calls[0],['speech','elevenlabs','TEST-ONLY-NOT-A-REAL-KEY','eleven_multilingual_v2','https://api.elevenlabs.io/v1']);assert.equal(screen.getByLabelText('ElevenLabs API key').value,'');
fail=true;fireEvent.change(screen.getByLabelText('ElevenLabs API key'),{target:{value:'TEST-ONLY-NOT-A-REAL-KEY'}});fireEvent.click(screen.getByRole('button',{name:'Save ElevenLabs provider'}));await screen.findByText('Credential store unavailable');assert.equal(saved,1);assert.equal(screen.getByLabelText('ElevenLabs API key').value,'TEST-ONLY-NOT-A-REAL-KEY');await act(async()=>{detail.open=false;fireEvent(detail,new dom.window.Event('toggle'));});assert.equal(screen.getByLabelText('ElevenLabs API key').value,'');cleanup();
render(React.createElement(ProviderConnection,{name:'openai',onSaved:async()=>{}}));assert.equal(screen.getByLabelText('OpenAI model').value,'gpt-image-1');cleanup();console.log('PASS explicit provider save, password fields, configured defaults, cleared key on save/collapse and truthful credential-store errors; no real provider calls');
