import {JSDOM} from 'jsdom';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'http://localhost:8000'});
for(const k of ['window','document','navigator','HTMLElement','HTMLInputElement','Event','MouseEvent','CustomEvent','File','FormData'])Object.defineProperty(globalThis,k,{value:dom.window[k],configurable:true});
await build({entryPoints:['src/ShareDialog.tsx'],outfile:'node_modules/.cache/share-dialog.cjs',bundle:true,platform:'node',format:'cjs',external:['react','react-dom'],logLevel:'silent'});
const require=createRequire(import.meta.url),React=require('react');
const {ShareDialog}=require('../node_modules/.cache/share-dialog.cjs');
const {render,screen,within}=await import('@testing-library/react');
const checks=[];let revealId='';let opened='';window.open=url=>{opened=url;};
render(React.createElement(ShareDialog,{assetId:'asset-123',fileName:'SceneForge-export.mp4',onClose:()=>{},onReveal:async id=>{revealId=id;}}));
assert.ok(screen.getByRole('dialog',{name:'Share exported video'}));checks.push('share dialog opens after export');
assert.equal(screen.getByRole('link',{name:/Download video/}).getAttribute('download'),'SceneForge-export.mp4');checks.push('dialog offers direct download with the export file name');
for(const platform of ['YouTube','TikTok','Instagram','Facebook'])assert.ok([...document.querySelectorAll('.share-destination')].find(card=>card.textContent.includes(platform))?.querySelector('button'));
checks.push('platform cards show upload next steps');
assert.ok(screen.getByText(/unverified API projects have upload restrictions/i));
assert.ok(screen.getByText(/developer app and TikTok audit approval/i));
assert.ok(screen.getByText(/eligible Professional accounts/i));checks.push('direct-upload limitations are disclosed');
await screen.getByRole('button',{name:'Open file location'}).click();assert.equal(revealId,'asset-123');checks.push('desktop file-location action delegates the exported asset id');
await screen.getByRole('button',{name:'Open TikTok'}).click();assert.equal(opened,'https://www.tiktok.com/upload');checks.push('platform action opens the correct destination');
console.log(`${checks.length} share dialog checks passed (${checks.join('; ')}).`);
