import React,{useState} from 'react';
import type {CensorRange} from './api';
export function wordMatches(words:[string,number,number][],list:string,offset=0){
 const norm=(s:string)=>s.normalize('NFKD').replace(/\p{M}/gu,'').toLocaleLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
 const wanted=new Set(list.split(/[,\n]+/).map(norm).filter(Boolean));
 const rows=words.filter(w=>wanted.has(norm(w[0]))).map(w=>({start_ms:Math.max(0,Math.round(w[1]+offset-40)),end_ms:Math.round(w[2]+offset+40),mode:'bleep' as const})).sort((a,b)=>a.start_ms-b.start_ms),out:CensorRange[]=[];
 for(const row of rows){const last=out[out.length-1];if(last&&row.start_ms<=last.end_ms)last.end_ms=Math.max(last.end_ms,row.end_ms);else out.push(row);}return out;
}
export function AudioCensor({ranges,sourceMs,onChange,disabled=false,words=[],wordOffset=0}:{ranges:CensorRange[];sourceMs:number;onChange:(rows:CensorRange[])=>void;disabled?:boolean;words?:[string,number,number][];wordOffset?:number}){
 const [start,setStart]=useState(0),[end,setEnd]=useState(.5),[mode,setMode]=useState<'bleep'|'mute'>('bleep'),[list,setList]=useState(''),[matches,setMatches]=useState<CensorRange[]|null>(null),[error,setError]=useState('');
 function add(rows:CensorRange[]){const next=[...ranges,...rows].sort((a,b)=>a.start_ms-b.start_ms);if(next.length>100||next.some(r=>r.end_ms-r.start_ms<20||r.end_ms>sourceMs||r.start_ms<0)||next.some((r,i)=>i>0&&r.start_ms<next[i-1].end_ms)){setError('Keep ranges inside the original file and remove overlaps before adding.');return;}onChange(next);setError('');setMatches(null);}
 return <section className="audio-card audio-censor" aria-label="Voice censoring"><h4>Voice censoring</h4><p className="hint">Replace selected parts with a bleep or silence. Times refer to the original file; trimming keeps them attached to the same sound. Other audio tracks remain audible.</p><fieldset disabled={disabled}><div className="audio-times"><label>From (s)<input aria-label="Censor start seconds" type="number" min={0} max={sourceMs/1000} step={.01} value={start} onChange={e=>setStart(Number(e.target.value))}/></label><label>To (s)<input aria-label="Censor end seconds" type="number" min={0} max={sourceMs/1000} step={.01} value={end} onChange={e=>setEnd(Number(e.target.value))}/></label></div><label>Replace with<select aria-label="Censor mode" value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="bleep">Bleep</option><option value="mute">Mute</option></select></label><button className="btn" onClick={()=>add([{start_ms:Math.round(start*1000),end_ms:Math.round(end*1000),mode}])}>Add censor range</button><details><summary>Find words in timed narration</summary><p className="hint">Requires narration word timings from auto captions. Matches use the existing transcript; listen and review their times before adding. Enter one word per line or separate with commas.</p><textarea aria-label="Censored word list" value={list} onChange={e=>{setList(e.target.value);setMatches(null);}}/><button className="btn" disabled={!words.length||!list.trim()} onClick={()=>setMatches(wordMatches(words,list,wordOffset).map(r=>({...r,end_ms:Math.min(sourceMs,r.end_ms),mode})))}>Review word matches</button>{!words.length&&<p className="hint">Word matching needs timed narration captions linked to this source. Add ranges manually for other clips.</p>}{matches&&<div role="status"><p>{matches.length} matches</p>{matches.map((r,i)=><p key={i}>{(r.start_ms/1000).toFixed(2)}–{(r.end_ms/1000).toFixed(2)} s · {r.mode}</p>)}<button className="btn" disabled={!matches.length} onClick={()=>add(matches)}>Add reviewed matches</button></div>}</details>{ranges.map((r,i)=><div className="censor-range" key={i}><span>{(r.start_ms/1000).toFixed(2)}–{(r.end_ms/1000).toFixed(2)} s · {r.mode}</span><button className="text-btn" aria-label={`Remove censor range ${i+1}`} onClick={()=>onChange(ranges.filter((_,k)=>k!==i))}>Remove</button></div>)}</fieldset>{error&&<p role="alert" className="form-error">{error}</p>}<p className="hint">Use Play clip in Scene audio to audition narration ranges; render other clips to audition. Render/export applies the exact ranges. Censoring sound does not hide caption words.</p></section>;
}
