import React,{useState,useRef,useEffect} from 'react';
import {Shot,api} from './api';
export function FramingControls({shot,save}:{shot:Shot;save:(f:()=>Promise<unknown>)=>Promise<boolean>}){
 const c=shot.crop_json||{x:0,y:0,width:1,height:1};
 const [crop,setCrop]=useState(c),[message,setMessage]=useState('');
 const initial=shot.motion_json.start||{x:.5,y:.5,scale:1},final=shot.motion_json.end||initial;
 const [start,setStart]=useState(initial),[end,setEnd]=useState(final);
 const drag=useRef<{x:number;y:number;crop:typeof crop;resize:boolean}|null>(null);
 const [playing,setPlaying]=useState(false),[progress,setProgress]=useState(0);
 useEffect(()=>{if(!playing)return;let id=0;const begin=performance.now();const tick=(now:number)=>{const t=Math.min(1,(now-begin)/2000);setProgress(t);if(t<1)id=requestAnimationFrame(tick);else setPlaying(false)};id=requestAnimationFrame(tick);return ()=>cancelAnimationFrame(id)},[playing]);
 const mix=(key:string)=>start[key]+(end[key]-start[key])*progress;
 const slider=(label:string,value:number,min:number,max:number,step:number,reset:number,change:(n:number)=>void)=><label className="range-control">{label}<div><input aria-label={label+' slider'} type="range" min={min} max={max} step={step} value={value} onChange={e=>change(+e.target.value)}/><input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e=>change(Math.max(min,Math.min(max,+e.target.value)))}/><button type="button" title={'Reset '+label} onClick={()=>change(reset)}>↺</button></div></label>;
 return <section className="framing-controls"><h3>Crop & focal zoom</h3><p className="hint">Crop percentages refer to the source image. Focal zoom uses Fill frame. Render to preview movement.</p>
 <div>{(['x','y','width','height'] as const).map(k=><React.Fragment key={k}>{slider('Crop '+k+' percent',Math.round(crop[k]*100),k==='x'||k==='y'?0:5,k==='x'?Math.round((1-crop.width)*100):k==='y'?Math.round((1-crop.height)*100):k==='width'?Math.round((1-crop.x)*100):Math.round((1-crop.y)*100),1,k==='x'||k==='y'?0:100,n=>setCrop({...crop,[k]:Math.min(n/100,k==='width'?1-crop.x:k==='height'?1-crop.y:k==='x'?1-crop.width:1-crop.height)}))}</React.Fragment>)}</div>
 <div className="crop-map" style={{position:'relative',touchAction:'none'}} onPointerMove={e=>{if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect(),v=drag.current;const dx=(e.clientX-v.x)/r.width,dy=(e.clientY-v.y)/r.height;setCrop(v.resize?{...v.crop,width:Math.max(.05,Math.min(1-v.crop.x,v.crop.width+dx)),height:Math.max(.05,Math.min(1-v.crop.y,v.crop.height+dy))}:{...v.crop,x:Math.max(0,Math.min(1-v.crop.width,v.crop.x+dx)),y:Math.max(0,Math.min(1-v.crop.height,v.crop.y+dy))});}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}><img draggable={false} src={api.assetStreamUrl(shot.asset_id)} style={{width:'100%',display:'block'}}/><div aria-label="Move crop rectangle" onPointerDown={e=>{e.currentTarget.parentElement!.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,crop:{...crop},resize:false}}} style={{position:'absolute',border:'2px solid #b6a0ff',left:crop.x*100+'%',top:crop.y*100+'%',width:crop.width*100+'%',height:crop.height*100+'%',boxSizing:'border-box',cursor:'move'}}><button aria-label="Resize crop rectangle" onPointerDown={e=>{e.stopPropagation();e.currentTarget.parentElement!.parentElement!.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,crop:{...crop},resize:true}}} style={{position:'absolute',bottom:-6,right:-6,width:14,height:14,padding:0,background:'#b6a0ff',cursor:'nwse-resize'}}/></div></div>
 <button className="btn" onClick={async()=>{if(crop.x+crop.width>1.00001||crop.y+crop.height>1.00001||Math.min(crop.width,crop.height)<.05){setMessage('Crop must fit within 100% of the source.');return;}setMessage('');await save(()=>api.updateShot(shot.id,{crop}));}}>Apply crop</button> <button className="text-btn" onClick={async()=>{setCrop({x:0,y:0,width:1,height:1});await save(()=>api.updateShot(shot.id,{crop:null}));}}>Reset crop</button>
 {(['Start','End'] as const).map(label=>{const value=label==='Start'?start:end,set=label==='Start'?setStart:setEnd;return <div key={label}><h4>{label} framing</h4>{['x','y','scale'].map(k=><React.Fragment key={k}>{slider(`${label} focal ${k}`,value[k],k==='scale'?1:0,k==='scale'?1.5:1,.01,k==='scale'?1:.5,n=>set({...value,[k]:n}))}</React.Fragment>)}<div className="focal-map" role="button" tabIndex={0} aria-label={label+' focal point'} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();set({...value,x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height});}} style={{position:'relative',cursor:'crosshair'}}><img src={api.assetStreamUrl(shot.asset_id)} style={{width:'100%',display:'block'}}/><span style={{position:'absolute',left:value.x*100+'%',top:value.y*100+'%',transform:'translate(-50%,-50%)',color:'#fff',textShadow:'0 0 4px black'}}>⊕</span></div></div>})}
 <div style={{overflow:'hidden',aspectRatio:'16/9',margin:'12px 0'}}><img src={api.assetStreamUrl(shot.asset_id)} style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:`${mix('x')*100}% ${mix('y')*100}%`,transform:`scale(${mix('scale')})`,transformOrigin:`${mix('x')*100}% ${mix('y')*100}%`}}/></div><button className="btn" disabled={playing} onClick={()=>{setProgress(0);setPlaying(true)}}>Preview movement</button><p className="hint">Motion sketch uses the source image. Apply and render the scene to check final framing and crop.</p>
 <button className="btn" onClick={()=>save(()=>api.updateShot(shot.id,{fit:'cover',motion:{type:'ken_burns',start,end}}))}>Apply focal movement</button>{message&&<p role="alert">{message}</p>}
 </section>
}
