import React,{useState,useRef,useEffect} from 'react';
import {Shot,api} from './api';
import {FeatureHelp} from './FeatureHelp';

type Crop={x:number;y:number;width:number;height:number};
type Focal={x:number;y:number;scale:number};
function PreviewImage({src,label,style,draggable}:{src:string;label:string;style?:React.CSSProperties;draggable?:boolean}){const [failed,setFailed]=useState(false);return failed?<div role="img" aria-label={label+' unavailable'} className="framing-image-fallback">Preview unavailable</div>:<img src={src} alt={label} draggable={draggable} onError={()=>setFailed(true)} style={style}/>;}

export function FramingControls({shot,save}:{shot:Shot;save:(f:()=>Promise<unknown>)=>Promise<boolean>}){
 const initialCrop:Crop=shot.crop_json||{x:0,y:0,width:1,height:1};
 const initialStart:Focal=shot.motion_json.start||{x:.5,y:.5,scale:1};
 const initialEnd:Focal=shot.motion_json.end||initialStart;
 const [crop,setCrop]=useState<Crop>(initialCrop),[message,setMessage]=useState('');
 const [start,setStart]=useState<Focal>(initialStart),[end,setEnd]=useState<Focal>(initialEnd);
 const drag=useRef<{x:number;y:number;crop:Crop;resize:boolean}|null>(null);
 const [playing,setPlaying]=useState(false),[progress,setProgress]=useState(0);
 // Refresh drafts when undo/redo or another editor action changes this shot.
 useEffect(()=>{setCrop(shot.crop_json||{x:0,y:0,width:1,height:1});setStart(shot.motion_json.start||{x:.5,y:.5,scale:1});setEnd(shot.motion_json.end||shot.motion_json.start||{x:.5,y:.5,scale:1});},[shot.id,shot.crop_json,shot.motion_json]);
 useEffect(()=>{if(!playing)return;let id=0;const begin=performance.now();const tick=(now:number)=>{const t=Math.min(1,(now-begin)/2000);setProgress(t);if(t<1)id=requestAnimationFrame(tick);else setPlaying(false)};id=requestAnimationFrame(tick);return ()=>cancelAnimationFrame(id)},[playing]);
 const mix=(key:keyof Focal)=>start[key]+(end[key]-start[key])*progress;
 const validCrop=(c:Crop)=>c.x+c.width<=1.00001&&c.y+c.height<=1.00001&&Math.min(c.width,c.height)>=.05;
 const commitCrop=async(c:Crop)=>{if(!validCrop(c)){setMessage('Crop must fit within 100% of the source.');return;}setMessage('');await save(()=>api.updateShot(shot.id,{crop:c}));};
 const commitFocal=async(which:'start'|'end',f:Focal)=>{setMessage('');const other=which==='start'?end:start;await save(()=>api.updateShot(shot.id,{fit:'cover',motion:{type:'ken_burns',start:which==='start'?f:other,end:which==='end'?f:other}}));};
 const slider=(label:string,value:number,min:number,max:number,step:number,reset:number,change:(n:number)=>void,commit:(n:number)=>void)=><label className="range-control">{label}<div><input aria-label={label+' slider'} type="range" min={min} max={max} step={step} value={value} onChange={e=>change(+e.target.value)} onPointerUp={e=>commit(+e.currentTarget.value)} onKeyUp={e=>commit(+e.currentTarget.value)}/><input aria-label={label} type="number" min={min} max={max} step={step} value={value} onChange={e=>change(Math.max(min,Math.min(max,+e.target.value)))} onBlur={e=>commit(+e.currentTarget.value)}/><button type="button" title={'Reset '+label} onClick={()=>{change(reset);commit(reset)}}>↺</button></div></label>;
 const fitNow=shot.fit||'cover';
 const fitRow=<div className="fit-choice"><span>Fill the frame</span><div className="segmented" role="radiogroup" aria-label="Fit">
  {([['cover','Fill (crop)'],['contain_blur','Fit + blurred background'],['contain','Fit + bars']] as const).map(([v,l])=><button key={v} role="radio" aria-checked={fitNow===v} className={fitNow===v?'selected':''} onClick={()=>save(()=>api.updateShot(shot.id,{fit:v}))}>{l}</button>)}</div>
  <p className="hint">{fitNow==='cover'?'Fills the whole frame; edges may be cropped. Crop and zoom movement below apply.':fitNow==='contain_blur'?'Shows the whole picture over a blurred copy of itself — the usual look for landscape clips in 9:16. Zoom movement applies with Fill only.':'Shows the whole picture with black bars. Zoom movement applies with Fill only.'}</p></div>;
 const thumb=api.assetThumbUrl(shot.asset_id,480);
 return <section className="framing-controls">{fitRow}<div className="section-heading"><h3>Crop & focal zoom</h3><FeatureHelp compact title="Crop and focal zoom" description="Crop the source frame or set start/end focal points for a Ken Burns pan and zoom." steps="Drag the crop boundary or edit its values. Set the start and end points on the preview, use Fill frame for focal zoom, then apply and render to check the movement."/></div><p className="hint">Crop percentages refer to the source image. Focal zoom uses Fill frame. Changes save when you release a slider or finish typing; Apply buttons are also available.</p>
 <div>{(['x','y','width','height'] as const).map(k=><React.Fragment key={k}>{slider('Crop '+k+' percent',Math.round(crop[k]*100),k==='x'||k==='y'?0:5,k==='x'?Math.round((1-crop.width)*100):k==='y'?Math.round((1-crop.height)*100):k==='width'?Math.round((1-crop.x)*100):Math.round((1-crop.y)*100),1,k==='x'||k==='y'?0:100,n=>setCrop(prev=>({...prev,[k]:Math.min(n/100,k==='width'?1-crop.x:k==='height'?1-crop.y:k==='x'?1-crop.width:1-crop.height)})),n=>{const next={...crop,[k]:Math.min(n/100,k==='width'?1-crop.x:k==='height'?1-crop.y:k==='x'?1-crop.width:1-crop.height)};setCrop(next);void commitCrop(next);})}</React.Fragment>)}</div>
 <div className="crop-map" style={{position:'relative',touchAction:'none'}} onPointerMove={e=>{if(!drag.current)return;const r=e.currentTarget.getBoundingClientRect(),v=drag.current,dx=(e.clientX-v.x)/r.width,dy=(e.clientY-v.y)/r.height;setCrop(v.resize?{...v.crop,width:Math.max(.05,Math.min(1-v.crop.x,v.crop.width+dx)),height:Math.max(.05,Math.min(1-v.crop.y,v.crop.height+dy))}:{...v.crop,x:Math.max(0,Math.min(1-v.crop.width,v.crop.x+dx)),y:Math.max(0,Math.min(1-v.crop.height,v.crop.y+dy))});}} onPointerUp={()=>{drag.current=null;void commitCrop(crop)}} onPointerCancel={()=>{drag.current=null}}><PreviewImage draggable={false} src={thumb} label="Video or image crop preview" style={{width:'100%',display:'block'}}/><div aria-label="Move crop rectangle" onPointerDown={e=>{e.currentTarget.parentElement!.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,crop:{...crop},resize:false}}} style={{position:'absolute',border:'2px solid #b6a0ff',left:crop.x*100+'%',top:crop.y*100+'%',width:crop.width*100+'%',height:crop.height*100+'%',boxSizing:'border-box',cursor:'move'}}><button aria-label="Resize crop rectangle" onPointerDown={e=>{e.stopPropagation();e.currentTarget.parentElement!.parentElement!.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,crop:{...crop},resize:true}}} style={{position:'absolute',bottom:-6,right:-6,width:14,height:14,padding:0,background:'#b6a0ff',cursor:'nwse-resize'}}/></div></div>
 <button className="btn" onClick={()=>void commitCrop(crop)}>Apply crop</button> <button className="text-btn" onClick={async()=>{const reset={x:0,y:0,width:1,height:1};setCrop(reset);await save(()=>api.updateShot(shot.id,{crop:null}));}}>Reset crop</button>
 {(['Start','End'] as const).map(label=>{const key=label.toLowerCase() as 'start'|'end',value=key==='start'?start:end,set=key==='start'?setStart:setEnd;return <div key={label}><h4>{label} framing</h4>{(['x','y','scale'] as const).map(k=><React.Fragment key={k}>{slider(`${label} focal ${k}`,value[k],k==='scale'?1:0,k==='scale'?1.5:1,.01,k==='scale'?1:.5,n=>set(prev=>({...prev,[k]:n})),n=>{const next={...value,[k]:n};set(next);void commitFocal(key,next);})}</React.Fragment>)}<div className="focal-map" role="button" tabIndex={0} aria-label={label+' focal point'} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect(),next={...value,x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};set(next);void commitFocal(key,next);}} style={{position:'relative',cursor:'crosshair'}}><PreviewImage src={thumb} label="Focal point preview" style={{width:'100%',display:'block'}}/><span style={{position:'absolute',left:value.x*100+'%',top:value.y*100+'%',transform:'translate(-50%,-50%)',color:'#fff',textShadow:'0 0 4px black'}}>⊕</span></div></div>})}
 <div style={{overflow:'hidden',aspectRatio:'16/9',margin:'12px 0'}}><PreviewImage src={thumb} label="Focal movement preview" style={{width:'100%',height:'100%',objectFit:'cover',objectPosition:`${mix('x')*100}% ${mix('y')*100}%`,transform:`scale(${mix('scale')})`,transformOrigin:`${mix('x')*100}% ${mix('y')*100}%`}}/></div><button className="btn" disabled={playing} onClick={()=>{setProgress(0);setPlaying(true)}}>Preview movement</button><p className="hint">Motion sketch uses the source image. Apply and render the scene to check final framing and crop.</p>
 <button className="btn" onClick={()=>save(()=>api.updateShot(shot.id,{fit:'cover',motion:{type:'ken_burns',start,end}}))}>Apply focal movement</button>{message&&<p role="alert">{message}</p>}
 </section>
}
