import React,{useEffect,useState} from 'react';
import {Asset,api} from './api';
import {Film,Volume2,X,Plus,Eye} from 'lucide-react';
export function MediaPool({projectId,version,disabled,onImport,onFolder,onAdd,onUse,canUse}:{projectId:string;version:number;disabled:boolean;onImport:()=>void;onFolder:()=>void;onAdd:(assets:Asset[])=>Promise<unknown>;onUse:(asset:Asset)=>Promise<unknown>;canUse:boolean}){
 const [assets,setAssets]=useState<Asset[]>([]),[chosen,setChosen]=useState<string[]>([]),[query,setQuery]=useState(''),[preview,setPreview]=useState<Asset|null>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;api.listAssets(projectId).then(a=>{if(live)setAssets(a);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[projectId,version]);
 const selected=assets.filter(a=>chosen.includes(a.id));
 return <section className="media-pool"><p className="hint">Import here first. Choose files, then add them to your edit.</p><div className="pool-actions"><button className="btn" disabled={disabled} onClick={onImport}>Import files</button><button className="btn" disabled={disabled} onClick={onFolder}>Folder</button></div><input aria-label="Search media pool" placeholder="Search media…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="hint">{assets.length} files · {selected.length} selected</p>
 <div className="pool-actions"><button className="btn btn-primary" disabled={disabled||!selected.length||selected.some(a=>a.type==='audio')} onClick={()=>void onAdd(selected)}>Add to timeline</button><button className="btn" disabled={disabled||!canUse||selected.length!==1} onClick={()=>void onUse(selected[0])}>Use in selected scene</button></div><p className="hint">Audio uses the selected scene’s narration lane. “Add to timeline” creates new scenes from images/videos.</p>
 {error&&<p role="alert">{error}</p>}
 <div className="pool-grid">{assets.filter(a=>a.original_filename.toLowerCase().includes(query.toLowerCase())).map(a=><article key={a.id} className={chosen.includes(a.id)?'chosen':''}><label><input type="checkbox" aria-label={`Select media ${a.original_filename}`} checked={chosen.includes(a.id)} onChange={e=>setChosen(ids=>e.target.checked?[...ids,a.id]:ids.filter(id=>id!==a.id))}/><div className="pool-thumb">{a.type==='image'?<img src={api.assetStreamUrl(a.id)} alt=""/>:a.type==='video'?<Film/>:<Volume2/>}</div><span title={a.original_filename}>{a.original_filename}</span></label><div><button aria-label={`Preview ${a.original_filename}`} onClick={()=>setPreview(a)}><Eye size={13}/></button><button disabled={disabled} aria-label={`Hide ${a.original_filename} from pool`} title="Hide from pool; keep existing scenes and source file" onClick={async()=>{try{await api.hideAsset(a.id);setAssets(old=>old.filter(x=>x.id!==a.id));setChosen(ids=>ids.filter(id=>id!==a.id));}catch(e:any){setError(e.message);}}}><X size={13}/></button></div></article>)}</div>
 {preview&&<div className="pool-preview" role="dialog" aria-label="Media preview" aria-modal="true"><header><strong>{preview.original_filename}</strong><button aria-label="Close media preview" onClick={()=>setPreview(null)}><X/></button></header>{preview.type==='image'?<img src={api.assetStreamUrl(preview.id)} alt={preview.original_filename}/>:preview.type==='video'?<video controls src={api.assetStreamUrl(preview.id)}/>:<audio controls src={api.assetStreamUrl(preview.id)}/>}<a href={api.assetDownloadUrl(preview.id)} download>Download source</a></div>}
 </section>
}
