import {CAMERA_MOTIONS} from './cameraMotions';
import {type Asset,type ProviderProfile,type VoiceOption} from './api';
import {type SceneSetupOptions} from './scriptSceneSetup';
import catalog from './captionStyles.json';
export function StorySceneSetup({options,onChange,assets,providers,voices,blocked,whisperReady,onEngine}:{options:SceneSetupOptions;onChange:(next:SceneSetupOptions)=>void;assets:Asset[];providers:ProviderProfile[];voices:VoiceOption[];blocked:boolean;whisperReady:boolean;onEngine:(id:string)=>void}){
 const set=(patch:Partial<SceneSetupOptions>)=>onChange({...options,...patch});const pictures=assets.filter(a=>['image','video'].includes(a.type)),localImages=providers.filter(p=>p.capability==='image'&&p.name==='local_sd'),speech=providers.filter(p=>p.capability==='speech'&&['kokoro','chatterbox','elevenlabs'].includes(p.name));
 return <fieldset className="story-scene-setup" disabled={blocked}><legend>Optional scene setup</legend><p className="hint">Choose what to prepare after adding scenes. Existing scenes stay unchanged. Local engines must already be installed and running. Open Settings → Providers to connect Kokoro, Chatterbox or ElevenLabs. Unconnected engines are listed but cannot generate. Reopen this dialog after connecting an engine.</p>
 <div className="story-setup-grid"><section className="audio-card"><h4>Pictures & motion</h4><label>Pictures<select aria-label="Script scene pictures" value={options.pictures} onChange={e=>set({pictures:e.target.value as SceneSetupOptions['pictures'],render:false})}><option value="none">Add pictures later</option><option value="pool" disabled={!pictures.length}>Use Media Pool pictures</option><option value="local" disabled={!localImages.length}>Generate with a local image engine</option></select></label>{options.pictures==='pool'&&<><div className="story-media-choices" role="group" aria-label="Script scene media choices">{pictures.map(a=><label key={a.id}><input type="checkbox" checked={options.mediaIds.includes(a.id)} onChange={e=>set({mediaIds:e.target.checked?[...options.mediaIds,a.id]:options.mediaIds.filter(id=>id!==a.id)})}/>{a.original_filename}</label>)}</div><p className="hint">Selected pictures repeat in order, one per scene. Videos keep their original movement.</p></>}{options.pictures==='local'&&<><label>Local image engine<select aria-label="Script local image engine" value={options.imageProviderId} onChange={e=>set({imageProviderId:e.target.value})}><option value="">Choose engine…</option>{localImages.map(p=><option key={p.id} value={p.id}>Stable Diffusion · {p.model}</option>)}</select></label><p className="hint">Edit each image prompt below. This uses your connected local Stable Diffusion service.</p></>}
 <label>Image motion<select aria-label="Script image motion" value={options.motion} onChange={e=>set({motion:e.target.value})}>{CAMERA_MOTIONS.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label></section>
 <section className="audio-card"><h4>Narration & captions</h4><label>Narration engine<select aria-label="Script narration engine" value={options.voiceEngine} onChange={e=>onEngine(e.target.value)}><option value="none">Generate narration later</option>{speech.map(p=><option key={p.id} value={p.id} disabled={p.configured===false}>{p.name==='elevenlabs'?'ElevenLabs · cloud (paid)':`${p.name} · local`}</option>)}{(['kokoro','chatterbox','elevenlabs'] as const).filter(name=>!speech.some(p=>p.name===name)).map(name=><option key={name} value={'unconfigured-'+name} disabled>{name==='elevenlabs'?'ElevenLabs · add API key in Settings':name+' · connect in Settings'}</option>)}<option value="diagnostic">Diagnostic espeak voice · robotic</option></select></label>{!['none','diagnostic'].includes(options.voiceEngine)&&<label>Voice<select aria-label="Script narration voice" value={options.voice} onChange={e=>set({voice:e.target.value})}><option value="">Choose voice…</option>{voices.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label>}
 {speech.find(p=>p.id===options.voiceEngine)?.name==='elevenlabs'&&<label className="switch-label paid-narration-choice"><input type="checkbox" aria-label="Allow paid ElevenLabs narration for this batch" checked={!!options.paidNarrationConfirmed} onChange={e=>set({paidNarrationConfirmed:e.target.checked})}/> Generate this batch with my ElevenLabs account (uses paid credits on Add scenes).</label>}
 <label>Language<select aria-label="Script setup language" value={options.language} onChange={e=>set({language:e.target.value as SceneSetupOptions['language']})}><option value="auto">English / Arabic by scene</option><option value="en">English</option><option value="ar">Arabic</option></select></label><p className="hint">Use Chatterbox or a compatible ElevenLabs model for Arabic. No narration engine is chosen automatically.</p>
 <label>Caption timing<select aria-label="Script caption timing" value={options.captions} onChange={e=>set({captions:e.target.value as SceneSetupOptions['captions']})}><option value="keep">Keep imported caption text</option><option value="script">Split script into caption boxes · estimated timing</option><option value="local" disabled={!whisperReady}>Transcribe audio · local Whisper</option></select></label><p className="hint">Estimated boxes need timing review. Local transcription uses the installed Whisper model; download it in Settings first.</p>
 <label>Caption style<select aria-label="Script caption style" value={options.style} onChange={e=>set({style:e.target.value})}><option value="">Project default</option>{catalog.groups.map(group=><optgroup key={group} label={group}>{catalog.styles.filter(s=>s.group===group).map(s=><option key={s.name} value={s.name}>{s.name}</option>)}</optgroup>)}</select></label></section></div>
 <div className="story-setup-footer"><label>Scene length without narration (s)<input type="number" aria-label="Script scene seconds" min={1} max={120} step={1} value={options.seconds} onChange={e=>set({seconds:Math.max(1,Math.min(120,Number(e.target.value)||4))})}/></label><label className="switch-label"><input type="checkbox" aria-label="Render imported scenes" checked={options.render} disabled={options.pictures==='none'} onChange={e=>set({render:e.target.checked})}/> Render scenes after setup</label></div><p className="hint">Generated narration sets each scene’s length. Undo removes the whole imported batch; Redo restores it without generating again.</p></fieldset>;
}
