import React,{useState} from 'react';
import {previewFontFamily} from './fonts';
import {TextLayer} from './api';
export const ANIMATIONS=['none','fade','slide','slide-right','slide-up','slide-down','zoom','reveal','typewriter','blur','glitch'];
export type TitleDesign={text:string;background:string;background2:string;gradient:boolean;duration:number;layer:TextLayer};
export function TitleDesigner({width,height,busy,onClose,onCreate}:{width:number;height:number;busy:boolean;onClose:()=>void;onCreate:(d:TitleDesign)=>void}){
 const [d,setD]=useState<TitleDesign>({text:'Chapter 1',background:'#000000',background2:'#362657',gradient:false,duration:5,layer:{id:'preview',text:'Chapter 1',x:50,y:50,size:96,color:'#ffffff',bold:true,start_ms:0,end_ms:0,animation:'fade',animation_ms:800,exit_ms:500,family:'Noto Naskh Arabic',outline_width:0,shadow:0,align:'center'}});
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[rendering,setRendering]=useState(false);
 const patch=(v:Partial<TitleDesign>)=>{setD({...d,...v});setUrl(u=>{if(u)URL.revokeObjectURL(u);return '';});};
 const layer=(v:Partial<TextLayer>)=>patch({layer:{...d.layer,...v}});
 React.useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 async function preview(){setRendering(true);setError('');try{const r=await fetch('/api/title-preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...d,width,height,layer:{...d.layer,text:d.text}})});if(!r.ok)throw Error(await r.text());setUrl(URL.createObjectURL(await r.blob()));}catch(e){setError(String(e));}finally{setRendering(false)}}
 const presets=[{name:'Chapter',color:'#ffffff',bg:'#000000',y:50,animation:'fade'},{name:'Lower third',color:'#ffffff',bg:'#172332',y:80,animation:'slide'},{name:'Typewriter',color:'#a2ffd3',bg:'#0a1713',y:50,animation:'typewriter'},{name:'Headline',color:'#ffe29a',bg:'#352041',y:40,animation:'zoom'}];
 return <div className="drawer-backdrop" onClick={()=>!busy&&onClose()}><section className="drawer title-designer" role="dialog" aria-modal="true" aria-label="Create title card" onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={onClose} disabled={busy}>Close</button><h3>Create title card</h3><div className="title-presets">{presets.map(p=><button key={p.name} onClick={()=>patch({background:p.bg,layer:{...d.layer,color:p.color,y:p.y,animation:p.animation}})} style={{background:p.bg,color:p.color}}><strong>Aa</strong>{p.name}</button>)}</div>
 {url?<video src={url} controls autoPlay loop className="title-preview"/>:<div className="title-preview" style={{position:'relative',aspectRatio:`${width}/${height}`,background:d.gradient?`linear-gradient(135deg,${d.background},${d.background2})`:d.background}}><span dir="auto" style={{position:'absolute',left:d.layer.x+'%',top:d.layer.y+'%',transform:`translate(${d.layer.align==='left'?0:d.layer.align==='right'?-100:-50}%,-50%)`,fontFamily:previewFontFamily(d.layer.family),fontSize:`${d.layer.size/width*100}cqw`,fontWeight:d.layer.bold?700:400,color:d.layer.color,textAlign:d.layer.align as any,textShadow:d.layer.shadow?'2px 2px 3px black':'none',WebkitTextStroke:`${(d.layer.outline_width||0)/4}px black`,whiteSpace:'pre-wrap',maxWidth:'95%'}}>{d.text}</span></div>}
 <button className="btn" disabled={rendering||!d.text.trim()} onClick={()=>void preview()}>{rendering?'Rendering preview…':'Play rendered preview'}</button><p className="hint">Layout preview is approximate. Play rendered preview checks the actual title animation.</p>{error&&<p role="alert">{error}</p>}
 <label>Title<textarea aria-label="Title card text" dir="auto" value={d.text} maxLength={2000} onChange={e=>patch({text:e.target.value})}/></label>
 <div className="designer-grid"><label>Font<select value={d.layer.family} onChange={e=>layer({family:e.target.value})}><option>Noto Naskh Arabic</option><option>Noto Sans Arabic</option><option>Noto Sans</option></select></label><label>Alignment<select value={d.layer.align} onChange={e=>layer({align:e.target.value})}>{['left','center','right'].map(v=><option key={v}>{v}</option>)}</select></label><label>Text color<input type="color" value={d.layer.color} onChange={e=>layer({color:e.target.value})}/></label><label>Background<input aria-label="Title card background" type="color" value={d.background} onChange={e=>patch({background:e.target.value})}/></label><label><input type="checkbox" checked={d.gradient} onChange={e=>patch({gradient:e.target.checked})}/>Gradient</label>{d.gradient&&<label>Second color<input type="color" value={d.background2} onChange={e=>patch({background2:e.target.value})}/></label>}<label><input type="checkbox" checked={d.layer.bold} onChange={e=>layer({bold:e.target.checked})}/>Bold</label>
 {(['size','x','y','outline_width','shadow'] as const).map(k=><label key={k}>{({size:'Font size',x:'Horizontal position',y:'Vertical position',outline_width:'Outline',shadow:'Shadow'})[k]}<input type="range" min={k==='size'?12:0} max={k==='size'?200:k==='outline_width'||k==='shadow'?10:100} value={Number(d.layer[k]||0)} onChange={e=>layer({[k]:+e.target.value})}/><output>{d.layer[k]}</output></label>)}
 <label>Animation<select aria-label="Title card animation" value={d.layer.animation} onChange={e=>layer({animation:e.target.value})}>{ANIMATIONS.map(v=><option key={v}>{v}</option>)}</select></label><label>Entrance (seconds)<input type="number" min={.1} max={10} step={.1} value={(d.layer.animation_ms||800)/1000} onChange={e=>layer({animation_ms:Math.max(100,Math.min(10000,+e.target.value*1000))})}/></label><label>Exit fade (seconds)<input type="number" min={0} max={10} step={.1} value={(d.layer.exit_ms||0)/1000} onChange={e=>layer({exit_ms:Math.max(0,Math.min(10000,+e.target.value*1000))})}/></label><label>Card duration (seconds)<input type="number" min={.5} max={60} step={.1} value={d.duration} onChange={e=>patch({duration:Math.max(.5,Math.min(60,+e.target.value))})}/></label></div><p className="hint">Hold time: {Math.max(0,d.duration-(d.layer.animation_ms||0)/1000-(d.layer.exit_ms||0)/1000).toFixed(1)}s. Entrance and exit are shortened to fit short cards.</p>
 <button className="btn btn-primary" disabled={busy||!d.text.trim()} onClick={()=>onCreate(d)}>Create title card</button></section></div>
}
