import {useEffect,useMemo,useRef,useState} from 'react';
import {CheckCircle2,Clapperboard,Download,ExternalLink,Film,HelpCircle,LoaderCircle,Plus,RefreshCw,Settings,Sparkles,Subtitles,Upload,X} from 'lucide-react';
import {api,type Asset,type Job,type LocalVideoSystem,type Project,type ProviderProfile,type VideoGenerationRequest,type VideoModel} from './api';

type Props={project:Project;selectedSceneId:string|null;onClose:()=>void;onOpenSettings:()=>void;onAdd:(assetId:string,placement:'after'|'inside')=>Promise<string|void>;onCaptions:(sceneId:string)=>Promise<void>};
const ratioSize:Record<string,[number,number]>={'16:9':[1280,720],'9:16':[720,1280],'1:1':[1024,1024]};
const money=(n:number)=>'$'+n.toFixed(2);
const COMFY_INSTALL='https://docs.comfy.org/get_started/introduction';
const GOOGLE_KEY='https://aistudio.google.com/app/apikey';
const GOOGLE_KEY_GUIDE='https://ai.google.dev/gemini-api/docs/api-key';
const RUNWAY_CONSOLE='https://dev.runwayml.com/';
const RUNWAY_KEY_GUIDE='https://docs.dev.runwayml.com/guides/setup/';
function openExternal(url:string){const desktop=(window as any).sceneforgeDesktop;if(desktop?.openExternal){void desktop.openExternal(url);return;}window.open(url,'_blank','noopener,noreferrer');}
const modelRates=(model:VideoModel)=>{
  if(model.kind==='local')return 'No provider fee';
  const entries=typeof model.price_per_second==='number'?[['all',model.price_per_second] as [string,number]]:Object.entries(model.price_per_second);
  return entries.map(([resolution,rate])=>`${resolution==='all'?'':resolution+' '}${money(rate)}/sec`).join(' · ');
};

export default function VideoGenerationPanel({project,selectedSceneId,onClose,onOpenSettings,onAdd,onCaptions}:Props){
  const [models,setModels]=useState<VideoModel[]>([]),[pricesChecked,setPricesChecked]=useState(''),[providerProfiles,setProviderProfiles]=useState<ProviderProfile[]>([]);
  const [provider,setProvider]=useState('local_comfy'),[modelId,setModelId]=useState('wan2.1-t2v-1.3b');
  const [prompt,setPrompt]=useState(''),[negative,setNegative]=useState('');
  const [ratio,setRatio]=useState(project.aspect),[customW,setCustomW]=useState(720),[customH,setCustomH]=useState(1280);
  const [resolution,setResolution]=useState('480p'),[duration,setDuration]=useState(5),[seed,setSeed]=useState(''),[candidateCount,setCandidateCount]=useState<1|2|3>(1);
  const [localStatus,setLocalStatus]=useState<{ready:boolean;message:string}>({ready:false,message:'Checking local engine…'});
  const [localChecking,setLocalChecking]=useState(false);
  const [localSystem,setLocalSystem]=useState<LocalVideoSystem|null>(null);
  const [jobId,setJobId]=useState<string|null>(null),[job,setJob]=useState<Job|null>(null),[assets,setAssets]=useState<Asset[]>([]),[selectedAssetId,setSelectedAssetId]=useState('');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[placement,setPlacement]=useState<'after'|'inside'>('after');
  const [addedSceneId,setAddedSceneId]=useState(''),[captionBusy,setCaptionBusy]=useState(false),[workflowBusy,setWorkflowBusy]=useState(false),[paidConfirm,setPaidConfirm]=useState(false);
  const workflowRef=useRef<HTMLInputElement>(null),loadedAssetIds=useRef(''),localModelTouched=useRef(false);
  useEffect(()=>{api.videoGenerationCatalog().then(data=>{setModels(data.models);setPricesChecked(data.prices_checked);}).catch(e=>setError(e.message));void refreshProviders();void checkLocalEngine();void api.localVideoSystem().then(setLocalSystem).catch(()=>setLocalSystem(null));const refresh=()=>{void refreshProviders();void checkLocalEngine();};window.addEventListener('sceneforge:providers-changed',refresh);return()=>window.removeEventListener('sceneforge:providers-changed',refresh);},[]);
  async function refreshProviders(){try{setProviderProfiles(await api.listProviders());}catch{setProviderProfiles([]);}}
  async function checkLocalEngine(){setLocalChecking(true);try{setLocalStatus(await api.localVideoStatus());}catch{setLocalStatus({ready:false,message:'Could not check local ComfyUI.'});}finally{setLocalChecking(false);}}
  const providerModels=useMemo(()=>models.filter(m=>m.provider===provider),[models,provider]);
  const model=providerModels.find(m=>m.id===modelId)||providerModels[0];
  const cloudProfile=providerProfiles.find(p=>p.capability==='video'&&p.name===provider);
  const recommendedModelId=localSystem?.recommended_model_ids?.[0]||'wan2.1-t2v-1.3b';
  useEffect(()=>{if(provider!=='local_comfy'||!localSystem?.detected||localModelTouched.current)return;const suggested=providerModels.find(item=>item.id===recommendedModelId);if(suggested)setModelId(suggested.id);},[provider,providerModels,localSystem,recommendedModelId]);
  useEffect(()=>{if(!models.length)return;const first=models.find(m=>m.provider===provider);if(first&&!models.some(m=>m.id===modelId&&m.provider===provider))setModelId(first.id);},[models,provider,modelId]);
  useEffect(()=>{if(!model)return;
    if(!model.ratios.includes(ratio))setRatio(model.ratios.includes(project.aspect)?project.aspect:model.ratios[0]);
    if(!model.resolutions.includes(resolution))setResolution(model.resolutions[0]);
    if(model.durations.length){if(!model.durations.includes(duration))setDuration(model.durations[0]);}
    else setDuration(Math.max(model.duration_min,Math.min(model.duration_max,duration)));
  },[model?.id]);
  const outputDims=useMemo(()=>{
    if(ratio==='custom')return [customW,customH];
    if(model?.kind==='local'){
      const tier=resolution==='480p'?480:resolution==='1080p'?1088:resolution==='4k'?2160:720;
      if(ratio==='1:1')return [tier,tier];
      if(ratio==='9:16')return [tier===480?480:tier===1088?1088:tier,tier===480?832:tier===1088?1920:1280];
      return [tier===480?832:tier===1088?1920:tier,tier===480?480:tier===1088?1088:720];
    }
    return ratioSize[ratio]||ratioSize[project.aspect]||ratioSize['16:9'];
  },[ratio,customW,customH,model?.kind,resolution,project.aspect]);
  const unitCost=useMemo(()=>{
    if(!model)return null;const rate=typeof model.price_per_second==='number'?model.price_per_second:model.price_per_second[resolution];
    return rate===undefined?null:{total:rate*duration,rate};
  },[model,resolution,duration]);
  const cost=unitCost?{...unitCost,total:unitCost.total*candidateCount}:null;
  const customDimensionsValid=ratio!=='custom'||(Number.isInteger(customW)&&Number.isInteger(customH)&&customW>=256&&customH>=256&&customW<=4096&&customH<=4096&&customW%16===0&&customH%16===0);
  const seedValid=seed.trim()===''||(Number.isInteger(Number(seed))&&Number(seed)>=0&&Number(seed)<=4294967295);
  useEffect(()=>{if(!jobId){setJob(null);return;}
    let stop=false;let timer:ReturnType<typeof setInterval>;
    const check=()=>api.getJob(jobId).then(next=>{if(stop)return;setJob(next);const ids=next.result_asset_ids?.length?next.result_asset_ids:(next.artifact_asset_id?[next.artifact_asset_id]:[]);const key=ids.join(',');if(key&&key!==loadedAssetIds.current){loadedAssetIds.current=key;Promise.all(ids.map(id=>api.getAsset(id).catch(()=>null))).then(rows=>{if(stop||loadedAssetIds.current!==key)return;const ready=rows.filter((item):item is Asset=>!!item);setAssets(ready);setSelectedAssetId(current=>ready.some(a=>a.id===current)?current:(ready[0]?.id||''));});}if(['succeeded','failed','cancelled'].includes(next.status)){setPaidConfirm(false);clearInterval(timer);}}).catch(()=>{});
    void check();timer=setInterval(()=>void check(),1800);return()=>{stop=true;clearInterval(timer);};
  },[jobId]);
  const asset=assets.find(item=>item.id===selectedAssetId)||assets[0]||null;
  const active=!!job&&['queued','running','cancelling'].includes(job.status);
  const costLabel=model?.kind==='local'?`No provider fee · ${candidateCount} local ${candidateCount===1?'render':'renders'}`:cost?`Estimated ${money(cost.total)} USD${candidateCount>1?` total for ${candidateCount} videos`:''}${model?.provider==='runway'?` · ${Math.round(cost.total/0.01)} credits`:''}`:'Choose a supported quality';
  const canGenerate=!!model&&prompt.trim().length>0&&!active&&!busy&&customDimensionsValid&&seedValid&&(!model.workflow_imported||model.kind!=='local'||localStatus.ready)&&(model.kind==='local'?model.workflow_imported:!!cost&&paidConfirm&&!!cloudProfile?.configured);
  const generateDisabledReason=!model?'Choose a video model.':active?'Generation is already running.':busy?'Starting generation…':model.kind==='local'&&!model.workflow_imported?`Import the API workflow for ${model.name} above to enable Generate.`:model.kind==='local'&&!localStatus.ready?'Start ComfyUI, then click Check again.':!prompt.trim()?'Enter a prompt to enable Generate.':!customDimensionsValid?'Fix the custom dimensions to continue.':!seedValid?'Enter a valid seed or leave it blank for a random seed.':model.kind==='cloud'&&!cloudProfile?.configured?'Connect this provider in Settings → Providers.':model.kind==='cloud'&&!paidConfirm?'Review and confirm the estimated charge above.':'';
  function chooseProvider(next:string){if(next==='local_comfy')localModelTouched.current=false;setProvider(next);setPaidConfirm(false);setError('');}
  async function importWorkflow(file?:File){if(!file||!model||model.kind!=='local')return;setWorkflowBusy(true);setError('');try{await api.importLocalVideoWorkflow(model.id,file);setModels(ms=>ms.map(m=>m.id===model.id?{...m,workflow_imported:true}:m));}catch(e:any){setError(e.message);}finally{setWorkflowBusy(false);if(workflowRef.current)workflowRef.current.value='';}}
  async function generate(){if(!model||!canGenerate)return;setError('');setAssets([]);setSelectedAssetId('');loadedAssetIds.current='';setAddedSceneId('');setBusy(true);
    try{const [width,height]=outputDims;const request:VideoGenerationRequest={provider,model:model.id,prompt:prompt.trim(),negative_prompt:negative.trim(),aspect_ratio:ratio,width,height,duration_seconds:duration,resolution,seed:seed.trim()?Number(seed):null,candidate_count:candidateCount,confirm_paid:model.kind==='cloud'&&paidConfirm};const started=await api.generateVideo(project.id,request);setJobId(started.job_id);}
    catch(e:any){setError(e.message);}finally{setBusy(false);}
  }
  async function addGenerated(){if(!asset)return;setBusy(true);setError('');try{const sceneId=await onAdd(asset.id,placement);if(sceneId)setAddedSceneId(sceneId);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function createCaptions(){if(!addedSceneId)return;setCaptionBusy(true);setError('');try{await onCaptions(addedSceneId);onClose();}catch(e:any){setError(e.message);}finally{setCaptionBusy(false);}}
  const progressMessage=job?.stage||'Preparing request…';
  return <div className="drawer-backdrop video-gen-backdrop" onClick={()=>!active&&onClose()}>
    <section className="drawer video-gen-panel" role="dialog" aria-modal="true" aria-label="Generate video from text" onClick={e=>e.stopPropagation()}>
      <header className="video-gen-header"><div className="video-gen-brand"><span className="video-gen-icon"><Clapperboard size={19}/></span><div><span className="eyebrow">SCENEFORGE STUDIO</span><h2>Generate video</h2><p>Create a clip from a written prompt, then edit it on your timeline.</p></div></div><button className="icon-btn" aria-label="Close video generation" disabled={active} onClick={onClose}><X size={17}/></button></header>

      <section className="video-gen-section"><div className="video-gen-section-title"><span>01</span><div><h3>Choose an engine</h3><p>Local models run on your computer. Cloud models are billed by their provider.</p></div></div>
        <div className="video-gen-provider-row" role="tablist" aria-label="Video provider">
          {[['local_comfy','Local'],['google_veo','Google Veo'],['runway','Runway']].map(([id,label])=><button type="button" key={id} role="tab" aria-selected={provider===id} className={provider===id?'active':''} disabled={active} onClick={()=>chooseProvider(id)}>{id==='local_comfy'?<Film size={15}/>:<Sparkles size={15}/>} {label}</button>)}
        </div>
        {providerModels.length>0&&<label className="control-label video-gen-model">Model<select aria-label="Video model" value={model?.id||''} disabled={active} onChange={e=>{if(provider==='local_comfy')localModelTouched.current=true;setModelId(e.target.value);setPaidConfirm(false);}}>{providerModels.map(m=><option value={m.id} key={m.id}>{m.name}{m.kind==='local'&&m.id===recommendedModelId?' · recommended for this GPU':''} · {modelRates(m)}</option>)}</select></label>}
        {model&&<div className={`video-gen-model-card ${model.kind}`}><div className="video-gen-model-top"><strong>{model.name}{model.kind==='local'&&model.id===recommendedModelId&&<em className="video-gen-recommended">Suggested for this computer</em>}</strong><span className={model.kind==='local'?'local-price':''}>{costLabel}</span></div><p>{model.requirements}</p>{model.kind==='local'&&localSystem&&<p className="video-gen-hardware"><strong>{localSystem.detected?`${localSystem.gpu_name} · ${localSystem.vram_gb} GB VRAM`:'GPU check'}</strong><span>{localSystem.message}</span></p>}<small className="video-gen-rate-list">{model.kind==='cloud'?'Published rates: ':'Provider cost: '}{modelRates(model)}{model.kind==='cloud'?` · checked ${pricesChecked||'recently'}`:''}</small><div className="video-gen-model-links"><button type="button" onClick={()=>openExternal(model.workflow_url)}><ExternalLink size={13}/> {model.kind==='local'?'Model & workflow guide':'API documentation'}</button>{model.terms_url&&<button type="button" onClick={()=>openExternal(model.terms_url!)}><ExternalLink size={13}/> Model terms</button>}</div>{model.kind==='cloud'&&<small>{model.cost_note} Estimate is not a guarantee of the provider's final charge.</small>}</div>}
        {model?.kind==='cloud'&&<div className="video-gen-local-setup"><p className="hint">{cloudProfile?.configured?'Your provider is connected. Its key is stored in your operating system credential store.':'Connect '+(provider==='google_veo'?'Google AI Studio':'Runway')+' in Settings before generating. The API key stays in your operating system credential store.'}</p><button className="btn" onClick={onOpenSettings}><Settings size={14}/>{cloudProfile?.configured?'Manage provider settings':'Open provider settings'}</button><details className="video-gen-setup-guide"><summary>Step-by-step API key setup</summary>{provider==='google_veo'?<ol><li>Sign in to Google AI Studio and select or import a Google Cloud project.</li><li>Open API Keys and create a current Gemini API key for that project. Google’s key types and restrictions change; follow its current key guide, especially if a previously created key stops working.</li><li>Check that Veo is available for your account and review current billing, region and quota limits.</li><li>In SceneForge, open Settings → Providers, choose Google video, paste the key, and save.</li></ol>:<ol><li>Sign up for Runway Dev and create a project for SceneForge.</li><li>Open the project’s API Keys tab, create a key and copy it immediately; Runway only shows it once.</li><li>Add API credits to the project. Runway currently documents a $10 minimum purchase for API use; check the latest billing page.</li><li>In SceneForge, open Settings → Providers, choose Runway video, paste the key, and save.</li><li>Check the selected model’s credit rate before confirming each generation.</li></ol>}<div className="video-gen-model-links"><button className="video-gen-link-button" type="button" onClick={()=>openExternal(provider==='google_veo'?GOOGLE_KEY_GUIDE:RUNWAY_KEY_GUIDE)}><ExternalLink size={13}/> Read official key instructions</button><button className="video-gen-link-button" type="button" onClick={()=>openExternal(provider==='google_veo'?GOOGLE_KEY:RUNWAY_CONSOLE)}><ExternalLink size={13}/>{provider==='google_veo'?'Open Google AI Studio API keys':'Open Runway developer console'}</button></div></details></div>}
        {provider==='local_comfy'&&<div className="video-gen-local-setup"><div className={`video-gen-engine-status ${localStatus.ready?'ready':''}`}><span className="status-dot"/>{localStatus.message}<button type="button" className="btn video-gen-check-button" disabled={localChecking} title="Check whether ComfyUI is reachable now" onClick={()=>void checkLocalEngine()}>{localChecking?<LoaderCircle size={13} className="spin"/>:<RefreshCw size={13}/>} {localChecking?'Checking…':'Check again'}</button><button type="button" className="btn video-gen-check-button" onClick={onOpenSettings}><Settings size={13}/> Settings</button></div>
          <details className="video-gen-setup-guide" open><summary>Local setup · step by step</summary><ol><li><b>Start ComfyUI.</b> Keep it running. SceneForge is already connected when the status above is green. If it is not, set its address under Settings → Providers (the usual local address is <code>http://127.0.0.1:8188</code>), then click <b>Check again</b>.</li><li><b>Load the model workflow in ComfyUI.</b> In ComfyUI, click the Templates icon in the left sidebar, or use <b>Workflow → Browse Workflow Templates</b>. Open the Video category and load <b>Wan 2.2 5B video generation</b> (the TI2V 5B workflow). If you already downloaded a regular workflow JSON, open it with <b>Workflow → Open</b> or drag the file onto the ComfyUI canvas. ComfyUI will show prompts for any missing model files; download those, then run the workflow once in ComfyUI to verify it works.</li><li><b>Export the API JSON.</b> In ComfyUI’s top menu, choose <b>File → Export Workflow (API)</b>. Some older versions label this <b>Save (API Format)</b>. Save the downloaded <code>.json</code> file somewhere easy to find. A regular workflow save is not the API export SceneForge needs.</li><li><b>Import it here.</b> Return to SceneForge, leave the same model selected, and click <b>Import API workflow</b> below. Choose the API-format JSON you just exported. The Generate button stays disabled until this workflow is imported for the selected model. <b>Check again</b> only checks the ComfyUI connection; it does not load a workflow or download model weights.</li></ol><button className="video-gen-link-button" type="button" onClick={()=>openExternal(COMFY_INSTALL)}><ExternalLink size={13}/> Open ComfyUI install guide</button>{model?.workflow_url&&<button className="video-gen-link-button" type="button" onClick={()=>openExternal(model.workflow_url)}><ExternalLink size={13}/> Open selected model workflow guide</button>}</details>
          <input ref={workflowRef} hidden type="file" accept=".json,application/json" onChange={e=>void importWorkflow(e.target.files?.[0])}/>
          <div className="video-gen-workflow-state"><span>{model?.workflow_imported?<><CheckCircle2 size={15}/> Workflow imported for this model</>:<>No API workflow imported for {model?.name||'this model'}</>}</span><button type="button" className="btn btn-primary" disabled={!model||workflowBusy} onClick={()=>workflowRef.current?.click()}>{workflowBusy?<LoaderCircle size={14} className="spin"/>:<Upload size={14}/>} {workflowBusy?'Importing…':'Import API workflow'}</button></div>
        </div>}
        {model?.kind==='cloud'&&<label className="video-gen-paid-confirm"><input type="checkbox" checked={paidConfirm} disabled={active} onChange={e=>setPaidConfirm(e.target.checked)}/><span>I understand this generation may cost <b>{cost?.total!==undefined?money(cost.total)+' USD':'the estimate shown above'}</b>. The provider's final billing and taxes may differ.</span></label>}
      </section>

      <section className="video-gen-section"><div className="video-gen-section-title"><span>02</span><div><h3>Describe the clip</h3><p>Specify the subject, movement, camera and visual style. Avoid asking the model to draw exact text.</p></div></div>
          <label className="control-label">Prompt<textarea value={prompt} disabled={active} onChange={e=>setPrompt(e.target.value)} maxLength={5000} placeholder="A close-up of a ceramic cup on a rainy windowsill. The camera slowly pushes in as raindrops slide down the glass; soft morning light, natural colors, cinematic depth of field…"/></label>
        {model?.kind==='local'&&<label className="control-label">Negative prompt <textarea className="video-gen-negative" value={negative} disabled={active} onChange={e=>setNegative(e.target.value)} maxLength={1000} placeholder="Optional: visual elements to avoid"/></label>}
        <div className="video-gen-controls">
          <label className="control-label">Aspect ratio<select value={ratio} disabled={active} onChange={e=>setRatio(e.target.value)}>{model?.ratios.map(r=><option value={r} key={r}>{r==='custom'?'Custom dimensions':r+(r===project.aspect?' · project':'' )}</option>)}</select></label>
          <label className="control-label">Duration {model?.durations.length?'(seconds)':''}{model?.durations.length?<select value={duration} disabled={active} onChange={e=>{setDuration(Number(e.target.value));setPaidConfirm(false);}}>{model.durations.map(d=><option key={d} value={d}>{d} seconds</option>)}</select>:<input type="number" min={model?.duration_min||1} max={model?.duration_max||30} step={1} value={duration} disabled={active} onChange={e=>{setDuration(Number(e.target.value));setPaidConfirm(false);}}/>}</label>
          <label className="control-label">Quality<select value={resolution} disabled={active} onChange={e=>{setResolution(e.target.value);setPaidConfirm(false);}}>{model?.resolutions.map(r=><option key={r} value={r}>{r}</option>)}</select></label>
          <label className="control-label">Seed <input type="number" min={0} max={4294967295} value={seed} disabled={active} placeholder="Random" onChange={e=>setSeed(e.target.value)}/></label>
        </div>
        <div className="video-gen-candidates-control"><label className="control-label">Generate options<select aria-label="Number of results" value={candidateCount} disabled={active} onChange={e=>{setCandidateCount(Number(e.target.value) as 1|2|3);setPaidConfirm(false);}}><option value={1}>1 result</option><option value={2}>2 results</option><option value={3}>3 results</option></select></label><p>{candidateCount>1?`SceneForge will generate ${candidateCount} separate takes so you can compare them. ${model?.kind==='cloud'?'The estimated total above includes every take.':'Each take uses another local generation run.'}`:'Generate a single result. Choose 2 or 3 to compare more takes.'}</p></div>
        {ratio==='custom'&&model?.kind==='local'&&<div className="video-gen-custom-dimensions"><label className="control-label">Width<input type="number" min={256} max={4096} step={16} value={customW} disabled={active} aria-invalid={!customDimensionsValid} onChange={e=>setCustomW(Number(e.target.value))}/></label><span>×</span><label className="control-label">Height<input type="number" min={256} max={4096} step={16} value={customH} disabled={active} aria-invalid={!customDimensionsValid} onChange={e=>setCustomH(Number(e.target.value))}/></label><small>{customDimensionsValid?'Use multiples of 16, from 256 to 4096 px.':'Enter whole pixel sizes from 256 to 4096, each divisible by 16.'}</small></div>}
        <div className="video-gen-audio-note"><HelpCircle size={14}/>{model?.native_audio===true?'This model can generate sound with the video. Use Text → Auto captions after adding it to transcribe spoken audio.':model?.native_audio===false?'This model normally generates picture only. Add or record audio in the existing Audio panel.':'Audio depends on the imported workflow. SceneForge will keep any audio track the workflow outputs; you can also add audio in the Audio panel.'}</div>
      </section>

      {error&&<div className="error-box" role="alert">{error}<button className="text-btn" onClick={()=>setError('')}>Dismiss</button></div>}
      {active&&<div className="video-gen-progress" role="status"><div className="video-gen-progress-head"><LoaderCircle size={17} className="spin"/><div><strong>{job?.status==='queued'?'Waiting for the engine': `Generating ${candidateCount===1?'your clip':`take ${assets.length+1} of ${candidateCount}`}`}</strong><span>{progressMessage}</span></div><button className="btn" onClick={()=>void api.cancelJob(jobId!).catch(e=>setError(e.message))}>Cancel</button></div><div className="video-gen-indeterminate"><span/></div><small>Provider progress is not exposed by this model; the bar indicates that the job is active.</small></div>}
      {job?.status==='failed'&&assets.length===0&&<div className="error-box" role="alert">Generation failed: {job.error||'The selected provider returned an error.'}</div>}
      {job?.status==='cancelled'&&<p className="hint" role="status">Generation cancelled.</p>}
      {job?.error&&assets.length>0&&<p className="video-gen-partial-note" role="status">Some requested takes did not finish: {job.error}</p>}
      {asset&&<section className="video-gen-result"><div className="video-gen-result-heading"><CheckCircle2 size={17}/><div><strong>{assets.length>1?`${assets.length} video options are ready`:'Generated video is ready'}</strong><span>{asset.original_filename} · {asset.width||'—'} × {asset.height||'—'} · {asset.duration_ms?`${(asset.duration_ms/1000).toFixed(1)} s`:''}</span></div><a className="text-btn" href={api.assetDownloadUrl(asset.id)} download><Download size={14}/> Download selected</a></div><video controls playsInline src={api.assetStreamUrl(asset.id)}/>
        {assets.length>1&&<div className="video-gen-candidate-list" role="radiogroup" aria-label="Choose a video result">{assets.map((candidate,index)=><button type="button" key={candidate.id} role="radio" aria-checked={candidate.id===asset.id} className={candidate.id===asset.id?'selected':''} onClick={()=>setSelectedAssetId(candidate.id)}><span className="video-gen-candidate-thumb"><video muted playsInline preload="metadata" src={api.assetStreamUrl(candidate.id)}/><b>{index+1}</b></span><span><strong>Take {index+1}</strong><small>{candidate.width||'—'} × {candidate.height||'—'} · {candidate.duration_ms?`${(candidate.duration_ms/1000).toFixed(1)} s`:''}</small></span></button>)}</div>}
        {!addedSceneId?<div className="video-gen-add-row"><label className="control-label">Add to timeline<select value={placement} onChange={e=>setPlacement(e.target.value as 'after'|'inside')}><option value="after">Create new scene after selected</option><option value="inside" disabled={!selectedSceneId}>Add inside selected scene</option></select></label><button className="btn btn-primary" disabled={busy} onClick={()=>void addGenerated()}><Plus size={15}/>{busy?'Adding…':'Add to timeline'}</button></div>:<div className="video-gen-caption-next"><span><CheckCircle2 size={15}/> Added to timeline. You can still edit the clip and its sound.</span><button className="btn" disabled={captionBusy} onClick={()=>void createCaptions()}>{captionBusy?<LoaderCircle size={14} className="spin"/>:<Subtitles size={14}/>} {captionBusy?'Generating captions…':'Generate captions & open Text'}</button></div>}
        {addedSceneId&&<p className="hint">Captions use local speech recognition by default, transcribing scene narration when present or video sound otherwise. This closes the generator and opens Text so you can edit each timed phrase, apply a caption style, and continue with the existing effects and overlays.</p>}
      </section>}
      {model?.kind==='local'&&model.native_audio&&<p className="video-gen-license-note">Model weights are downloaded separately and may have their own license and hardware requirements. Review the model terms before publishing generated work.</p>}
      <footer className="video-gen-footer"><button className="btn" disabled={active} onClick={onClose}>Close</button><div className="video-gen-footer-info"><span>{costLabel}</span>{!canGenerate&&generateDisabledReason&&<small role="status">{generateDisabledReason}</small>}</div><button className="btn btn-primary" disabled={!canGenerate} title={!canGenerate?generateDisabledReason:undefined} onClick={()=>void generate()}><Sparkles size={15}/>{busy?'Starting…':model?.kind==='cloud'?'Generate and confirm charge':candidateCount>1?`Generate ${candidateCount} videos`:'Generate video'}</button></footer>
    </section>
  </div>;
}
