"""The SceneForge sticker catalog (source of truth for scripts/build_sticker_library.py).

Each emoji entry is (emoji, name, tags). Names are unique and stable: the sticker id is the
slug of the name, and the 66 stickers from 0.7.0 RC8 keep their exact names (and so their ids).
Graphic stickers (badges, arrows, bubbles, ...) are drawn with Pillow in build_sticker_library.py.
"""

EMOJI: dict[str, list[tuple[str, str, str]]] = {
    "Smileys": [
        ("😀", "Grinning face", "reaction happy smile"), ("😂", "Laughing", "reaction funny tears"),
        ("🥳", "Party", "celebration confetti"), ("😍", "Heart eyes", "reaction love"),
        ("😮", "Wow", "reaction surprised"), ("🤔", "Thinking", "reaction question"),
        ("😎", "Cool", "reaction sunglasses"), ("😭", "Crying", "reaction sad"),
        ("🤩", "Starstruck", "reaction amazed wow"), ("🥹", "Pleading", "reaction emotional please"),
        ("😃", "Big smile", "happy grin joy"), ("😄", "Smiling eyes", "happy laugh joy"),
        ("😁", "Beaming", "grin happy teeth"), ("😆", "Squinting laugh", "laugh funny lol"),
        ("😅", "Sweat smile", "nervous relief phew"), ("🤣", "Rolling laughing", "lol rofl funny"),
        ("🙂", "Slight smile", "calm okay friendly"), ("😉", "Wink", "flirt joke wink"),
        ("😊", "Blush", "shy happy warm"), ("😇", "Halo", "angel innocent good"),
        ("🥰", "Smiling hearts", "love adore crush"), ("😘", "Blow kiss", "kiss love"),
        ("😋", "Yum", "tasty food delicious"), ("😛", "Tongue out", "silly playful"),
        ("😜", "Winking tongue", "silly crazy joke"), ("🤪", "Zany", "crazy silly wild"),
        ("🤗", "Hug", "hugging welcome warm"), ("🤭", "Hand over mouth", "oops giggle secret"),
        ("🤫", "Shush", "quiet secret silence"), ("🤨", "Raised eyebrow", "suspicious doubt skeptical"),
        ("😐", "Neutral", "meh blank"), ("😑", "Expressionless", "unimpressed meh"),
        ("😶", "No mouth", "speechless silent"), ("🙄", "Eye roll", "annoyed whatever"),
        ("😏", "Smirk", "smug sly"), ("😬", "Grimace", "awkward oops cringe"),
        ("😴", "Sleeping", "tired sleep bored zzz"), ("🤤", "Drool", "hungry want"),
        ("😷", "Mask", "sick health"), ("🤯", "Mind blown", "shock amazing explode"),
        ("🤠", "Cowboy", "yeehaw western"), ("🤓", "Nerd", "smart geek glasses"),
        ("🧐", "Monocle", "inspect curious detective"), ("😕", "Confused", "unsure puzzled"),
        ("😟", "Worried", "concern anxious"), ("😢", "Tear", "sad cry"),
        ("😱", "Scream", "shock horror scared"), ("😳", "Flushed", "embarrassed shock"),
        ("😡", "Angry", "mad rage"), ("🤬", "Cursing", "angry swear rage"),
        ("😈", "Devil smile", "mischief evil"), ("💀", "Skull", "dead lol dying"),
        ("👻", "Ghost", "boo spooky halloween"), ("🤖", "Robot", "ai bot tech"),
        ("💩", "Poop", "funny silly"), ("🤡", "Clown", "joke silly"),
        ("🥺", "Puppy eyes", "please beg cute"), ("🫠", "Melting", "embarrassed hot awkward"),
        ("😤", "Huff", "determined frustrated"), ("🥶", "Cold face", "freezing winter"),
        ("🥵", "Hot face", "heat summer spicy"), ("🤑", "Money face", "rich cash"),
        ("🫡", "Salute", "respect yes sir"),
    ],
    "Gestures": [
        ("👏", "Clap", "hands applause"), ("👍", "Thumbs up", "hands approve"),
        ("👎", "Thumbs down", "hands dislike"), ("🙏", "Thanks", "please hands"),
        ("💪", "Strong", "muscle power"), ("🙌", "Raise hands", "hands celebrate success"),
        ("👋", "Wave hello", "hands greeting"), ("🫶", "Heart hands", "hands love support"),
        ("👀", "Eyes", "look watch"), ("👌", "OK hand", "perfect fine okay"),
        ("✌️", "Victory", "peace two"), ("🤞", "Fingers crossed", "luck hope"),
        ("🤟", "Love you gesture", "ily hand"), ("🤘", "Rock on", "metal music"),
        ("🤙", "Call me", "phone shaka"), ("👈", "Point left", "direction hand"),
        ("👉", "Point right", "direction hand"), ("👆", "Point up", "direction hand above"),
        ("👇", "Point down", "direction hand below link"), ("☝️", "Index up", "one attention"),
        ("✋", "Raised hand", "stop high five"), ("🖐️", "Hand splayed", "five hand"),
        ("🖖", "Vulcan salute", "sci-fi greeting"), ("👊", "Fist bump", "punch bro"),
        ("✊", "Raised fist", "power solidarity"), ("🤝", "Handshake", "deal agreement partner"),
        ("🫰", "Finger heart", "love korean"), ("🤌", "Pinched fingers", "italian what"),
        ("✍️", "Writing hand", "write sign note"), ("🫵", "Point at you", "you viewer"),
    ],
    "Hearts": [
        ("❤️", "Heart", "love symbol red"), ("💖", "Sparkling heart", "love heart"),
        ("🧡", "Orange heart", "love"), ("💛", "Yellow heart", "love friendship"),
        ("💚", "Green heart", "love nature"), ("💙", "Blue heart", "love trust"),
        ("💜", "Purple heart", "love"), ("🖤", "Black heart", "love dark"),
        ("🤍", "White heart", "love pure"), ("🤎", "Brown heart", "love"),
        ("🩷", "Pink heart", "love cute"), ("💔", "Broken heart", "sad breakup"),
        ("💕", "Two hearts", "love couple"), ("💞", "Revolving hearts", "love romance"),
        ("💓", "Beating heart", "love pulse"), ("💗", "Growing heart", "love excited"),
        ("💘", "Heart arrow", "cupid valentine"), ("💝", "Heart gift", "valentine present"),
        ("❣️", "Heart exclamation", "love emphasis"), ("💌", "Love letter", "mail valentine"),
        ("❤️‍🔥", "Heart on fire", "passion love hot"),
    ],
    "Animals & nature": [
        ("🐱", "Cat", "animal pet"), ("🐶", "Dog", "animal pet"), ("🦋", "Butterfly", "nature"),
        ("🌸", "Blossom", "flower spring"), ("🦊", "Fox", "animal clever"), ("🐼", "Panda", "animal cute"),
        ("🐻", "Bear", "animal"), ("🐨", "Koala", "animal australia"), ("🐯", "Tiger", "animal wild"),
        ("🦁", "Lion", "animal king brave"), ("🐸", "Frog", "animal"), ("🐵", "Monkey", "animal"),
        ("🙈", "See no evil", "monkey shy oops"), ("🐧", "Penguin", "animal cold"),
        ("🐦", "Bird", "animal tweet"), ("🦄", "Unicorn", "magic fantasy"), ("🐝", "Bee", "insect honey busy"),
        ("🐢", "Turtle", "slow animal"), ("🐙", "Octopus", "sea animal"), ("🐬", "Dolphin", "sea animal"),
        ("🐳", "Whale", "sea animal"), ("🦈", "Shark", "sea danger"), ("🦉", "Owl", "wise night bird"),
        ("🐰", "Bunny", "rabbit easter cute"), ("🐷", "Pig", "animal farm"), ("🐮", "Cow", "animal farm"),
        ("🦖", "T-rex", "dinosaur"), ("🐍", "Snake", "animal"), ("🐞", "Ladybug", "insect luck"),
        ("🌻", "Sunflower", "flower summer"), ("🌹", "Rose", "flower love"), ("🌵", "Cactus", "desert plant"),
        ("🌴", "Palm tree", "tropical beach"), ("🍀", "Four-leaf clover", "luck"), ("🌱", "Seedling", "growth plant start"),
        ("🌷", "Tulip", "flower spring"),
    ],
    "Food": [
        ("☕", "Coffee", "drink break"), ("🍿", "Popcorn", "movie snack"), ("🍕", "Pizza", "food"),
        ("🍔", "Burger", "food fast"), ("🍟", "Fries", "food fast"), ("🌮", "Taco", "food mexican"),
        ("🍣", "Sushi", "food japanese"), ("🍜", "Noodles", "ramen food"), ("🍩", "Donut", "sweet dessert"),
        ("🍪", "Cookie", "sweet snack"), ("🎂", "Birthday cake", "party celebration"),
        ("🍰", "Cake slice", "dessert sweet"), ("🍦", "Ice cream", "dessert summer"),
        ("🍫", "Chocolate", "sweet"), ("🍓", "Strawberry", "fruit"), ("🍉", "Watermelon", "fruit summer"),
        ("🍎", "Apple", "fruit"), ("🍌", "Banana", "fruit"), ("🥑", "Avocado", "food healthy"),
        ("🌶️", "Hot pepper", "spicy chili"), ("🥐", "Croissant", "breakfast bakery"),
        ("🧋", "Bubble tea", "drink boba"), ("🍹", "Tropical drink", "cocktail summer"),
        ("🥤", "Soda cup", "drink"), ("🍵", "Tea", "drink green"), ("🥗", "Salad", "healthy food"),
    ],
    "Travel & places": [
        ("📍", "Pin", "location map"), ("🚀", "Rocket", "launch fast"), ("☀️", "Sun", "weather bright"),
        ("🌈", "Rainbow", "color pride"), ("✈️", "Airplane", "flight travel"), ("🚗", "Car", "drive road trip"),
        ("🚲", "Bicycle", "bike ride"), ("🚂", "Train", "railway travel"), ("🚢", "Ship", "cruise sea"),
        ("🏖️", "Beach", "vacation summer"), ("🏔️", "Mountain", "snow peak hike"), ("🏕️", "Camping", "outdoor tent"),
        ("🗺️", "World map", "travel location"), ("🌍", "Globe", "world earth"), ("🧭", "Compass", "direction explore"),
        ("🏠", "House", "home"), ("🏙️", "City", "skyline urban"), ("🗽", "Statue of Liberty", "new york usa"),
        ("🕌", "Mosque", "islam ramadan"), ("🎡", "Ferris wheel", "fun fair"), ("🌙", "Crescent moon", "night ramadan"),
        ("⛅", "Cloudy sun", "weather"), ("🌧️", "Rain", "weather"), ("🌊", "Wave", "sea surf ocean"),
        ("🧳", "Luggage", "travel trip"), ("🏛️", "Museum", "history classical building"),
    ],
    "Objects": [
        ("🎬", "Movie", "film video"), ("💡", "Idea", "light bulb tip"), ("🧩", "Puzzle piece", "idea problem solve"),
        ("📈", "Growth chart", "business growth up"), ("🎤", "Microphone", "creator speech music"),
        ("🎧", "Headphones", "audio podcast music"), ("👑", "Crown", "winner best creator"),
        ("💰", "Money", "cash finance"), ("🏆", "Trophy", "winner award"), ("🎯", "Target", "goal focus"),
        ("🧠", "Brain", "think smart"), ("📷", "Camera", "photo"), ("🎥", "Video camera", "film record"),
        ("📱", "Phone", "mobile smartphone"), ("💻", "Laptop", "computer work"), ("⌨️", "Keyboard", "typing computer"),
        ("🎮", "Game controller", "gaming play"), ("📚", "Books", "study read learn"), ("✏️", "Pencil", "write edit"),
        ("📌", "Pushpin", "pin note"), ("📎", "Paperclip", "attach"), ("🔑", "Key", "secret unlock"),
        ("🔒", "Lock", "secure private"), ("🔔", "Bell", "notification alert"), ("📣", "Megaphone", "announce loud"),
        ("📢", "Loudspeaker", "announcement"), ("⏰", "Alarm clock", "time wake"), ("⌛", "Hourglass", "time wait"),
        ("💎", "Gem", "diamond premium"), ("🎁", "Gift", "present giveaway"), ("🛒", "Shopping cart", "shop buy"),
        ("💳", "Credit card", "pay shop"), ("🧲", "Magnet", "attract"), ("🔍", "Magnifier", "search zoom find"),
        ("🛠️", "Tools", "fix build settings"), ("📦", "Package", "delivery box unboxing"),
        ("🗓️", "Calendar", "date schedule"), ("📊", "Bar chart", "stats data"), ("📉", "Falling chart", "down loss"),
        ("🔋", "Battery", "energy power"), ("🎙️", "Studio mic", "podcast record"), ("📸", "Camera flash", "photo snap"),
    ],
    "Symbols": [
        ("🔥", "Fire", "trending hot"), ("✨", "Sparkles", "magic shine"), ("⭐", "Star", "rating favorite"),
        ("💯", "100", "perfect score"), ("✅", "Check", "done correct"), ("❌", "Cross", "wrong no"),
        ("⚠️", "Warning", "alert caution"), ("❓", "Question", "help ask"), ("🎵", "Music", "sound audio"),
        ("💬", "Speech bubble", "comment message"), ("🌟", "Glow star", "star shine"), ("🚨", "Siren", "alert urgent"),
        ("🛑", "Stop", "halt"), ("▶️", "Play", "video start"), ("⏸️", "Pause", "video stop"),
        ("⚡", "Lightning", "energy fast power"), ("💥", "Impact", "comic boom action"),
        ("❗", "Exclamation", "important alert"), ("‼️", "Double exclamation", "important wow"),
        ("⁉️", "Interrobang", "what surprise"), ("💤", "Zzz", "sleep bored"), ("💢", "Anger symbol", "mad comic"),
        ("💦", "Sweat drops", "water splash"), ("💨", "Dash", "fast speed wind"), ("🆕", "New button", "new label"),
        ("🆒", "Cool button", "cool label"), ("🆓", "Free button", "free label"), ("🔝", "Top", "best top arrow"),
        ("♻️", "Recycle", "eco green"), ("⛔", "No entry", "forbidden stop"), ("🚫", "Prohibited", "no ban"),
        ("➕", "Plus", "add more"), ("➖", "Minus", "less remove"), ("✔️", "Check mark", "done yes tick"),
        ("🔴", "Red circle", "record live dot"), ("🟢", "Green circle", "online go dot"), ("🔵", "Blue circle", "dot"),
        ("🟡", "Yellow circle", "dot"), ("⏩", "Fast forward", "skip video"), ("⏪", "Rewind", "back video"),
        ("🔁", "Repeat", "loop again"), ("🔊", "Sound on", "volume audio loud"), ("🔇", "Mute", "silent no sound"),
        ("💭", "Thought bubble", "thinking idea"), ("🗯️", "Anger bubble", "shout comic"), ("🎶", "Notes", "music song"),
        ("♾️", "Infinity", "forever loop"),
    ],
    "Arrows & callouts": [
        ("⬆️", "Up arrow", "direction up"), ("⬇️", "Down arrow", "direction down"),
        ("⬅️", "Left arrow", "direction left back"), ("➡️", "Right arrow", "direction right next"),
        ("↗️", "Up-right arrow", "direction diagonal"), ("🔄", "Refresh arrows", "reload cycle"),
        ("↩️", "Return arrow", "back undo"),
    ],
    "Seasonal": [
        ("🎉", "Confetti", "party celebration"), ("🎄", "Christmas tree", "xmas holiday winter"),
        ("🎅", "Santa", "christmas xmas"), ("⛄", "Snowman", "winter snow"), ("❄️", "Snowflake", "winter cold"),
        ("🎃", "Pumpkin", "halloween autumn"), ("🦇", "Bat", "halloween night"), ("🕸️", "Spider web", "halloween spooky"),
        ("🎆", "Fireworks", "new year celebration"), ("🎇", "Sparkler", "new year celebration"),
        ("🧧", "Red envelope", "lunar new year"), ("🏮", "Lantern", "ramadan lunar festival"),
        ("🐣", "Hatching chick", "easter spring"), ("🍂", "Fallen leaves", "autumn fall"),
        ("🍁", "Maple leaf", "autumn canada"), ("🎊", "Confetti ball", "party celebrate"),
        ("🎈", "Balloon", "party birthday"), ("🎀", "Ribbon", "gift cute"), ("💐", "Bouquet", "flowers gift mother"),
        ("🎓", "Graduation cap", "school graduate"), ("🪔", "Diya lamp", "diwali festival"),
        ("🕯️", "Candle", "light memorial"), ("🌞", "Sun face", "summer happy"), ("🌕", "Full moon", "night eid"),
    ],
}

# Graphic stickers drawn with Pillow. kind -> drawing routine in build_sticker_library.py.
# (name, category, tags, kind, params)
GRAPHICS: list[tuple[str, str, str, str, dict]] = [
    # --- kept from RC8 (same names) ---
    ("Subscribe pill", "Social", "creator channel call to action", "pill", {"text": "SUBSCRIBE", "bg": "#E73549", "fg": "#FFFFFF", "icon": "bell"}),
    ("Follow banner", "Social", "creator social call to action", "banner", {"text": "FOLLOW", "bg": "#426BFF", "fg": "#FFFFFF"}),
    ("New badge", "Badges & labels", "label announcement latest", "pill", {"text": "NEW", "bg": "#FFE45C", "fg": "#242015"}),
    ("Wow burst", "Speech bubbles", "comic reaction impact", "burst", {"text": "WOW!", "bg": "#FF4D75", "fg": "#FFFFFF", "edge": "#FFFFFF"}),
    ("Quick tip", "Badges & labels", "label advice idea tutorial", "banner", {"text": "TIP", "bg": "#23B68B", "fg": "#FFFFFF"}),
    ("Sale badge", "Badges & labels", "label price promotion", "burst", {"text": "SALE", "bg": "#FF793D", "fg": "#FFFFFF", "edge": "#FFF4D3"}),
    # --- Social / subscribe ---
    ("Subscribe button", "Social", "subscribe channel youtube cta red", "button", {"text": "SUBSCRIBE", "bg": "#E62117", "fg": "#FFFFFF", "icon": "play"}),
    ("Subscribed grey", "Social", "subscribed done channel", "button", {"text": "SUBSCRIBED", "bg": "#E5E5E5", "fg": "#3A3A3A", "icon": "check"}),
    ("Like button", "Social", "like heart love cta", "button", {"text": "LIKE", "bg": "#FFFFFF", "fg": "#E0245E", "icon": "heart"}),
    ("Share button", "Social", "share send cta", "button", {"text": "SHARE", "bg": "#1D9BF0", "fg": "#FFFFFF", "icon": "share"}),
    ("Comment button", "Social", "comment reply cta", "button", {"text": "COMMENT", "bg": "#2B2D42", "fg": "#FFFFFF", "icon": "chat"}),
    ("Notification bell", "Social", "bell notify alerts", "icon_circle", {"icon": "bell", "bg": "#FFC83D", "fg": "#3B2A00"}),
    ("Follow plus", "Social", "follow add plus", "icon_circle", {"icon": "plus", "bg": "#FE2C55", "fg": "#FFFFFF"}),
    ("Link in bio", "Social", "link bio profile", "pill", {"text": "LINK IN BIO", "bg": "#7B5CFF", "fg": "#FFFFFF", "icon": "link"}),
    ("Swipe up", "Social", "swipe up story more", "stack", {"text": "SWIPE UP", "bg": "#FFFFFF", "fg": "#151515"}),
    ("Turn on notifications", "Social", "bell notify alerts cta", "pill", {"text": "TURN ON", "bg": "#151515", "fg": "#FFFFFF", "icon": "bell"}),
    ("Join now", "Social", "join cta member", "pill", {"text": "JOIN NOW", "bg": "#00B37E", "fg": "#FFFFFF"}),
    ("Tag a friend", "Social", "tag friend share", "pill", {"text": "TAG A FRIEND", "bg": "#FF8A00", "fg": "#FFFFFF"}),
    ("Save for later", "Social", "save bookmark", "pill", {"text": "SAVE THIS", "bg": "#0F172A", "fg": "#FFD84D", "icon": "bookmark"}),
    ("Watch till end", "Social", "watch end wait", "banner", {"text": "WATCH TILL THE END", "bg": "#111827", "fg": "#FFFFFF"}),
    # --- Badges & labels ---
    ("Hot badge", "Badges & labels", "hot trending label fire", "pill", {"text": "HOT", "bg": "#FF3B30", "fg": "#FFFFFF"}),
    ("Free badge", "Badges & labels", "free label price", "burst", {"text": "FREE", "bg": "#22C55E", "fg": "#FFFFFF", "edge": "#FFFFFF"}),
    ("Live badge", "Badges & labels", "live stream record", "live", {"text": "LIVE", "bg": "#E11D48", "fg": "#FFFFFF"}),
    ("Breaking news", "Badges & labels", "news breaking label lower third", "tag", {"text": "BREAKING NEWS", "bg": "#C8102E", "fg": "#FFFFFF", "bg2": "#FFFFFF", "fg2": "#C8102E"}),
    ("Limited offer", "Badges & labels", "sale limited offer promotion", "ribbon", {"text": "LIMITED OFFER", "bg": "#7C3AED", "fg": "#FFFFFF"}),
    ("Best seller", "Badges & labels", "best seller award", "seal", {"text": "BEST\nSELLER", "bg": "#F5B700", "fg": "#3A2A00"}),
    ("Top 10", "Badges & labels", "top ten list ranking", "seal", {"text": "TOP\n10", "bg": "#2563EB", "fg": "#FFFFFF"}),
    ("50% off", "Badges & labels", "sale discount half price", "burst", {"text": "50%\nOFF", "bg": "#FFD60A", "fg": "#1A1A1A", "edge": "#1A1A1A"}),
    ("Coming soon", "Badges & labels", "soon upcoming teaser", "pill", {"text": "COMING SOON", "bg": "#0EA5E9", "fg": "#FFFFFF"}),
    ("Update badge", "Badges & labels", "update new version", "pill", {"text": "UPDATE", "bg": "#14B8A6", "fg": "#FFFFFF"}),
    ("Pro tip", "Badges & labels", "tip advice expert", "banner", {"text": "PRO TIP", "bg": "#F59E0B", "fg": "#1F1300"}),
    ("Verified badge", "Badges & labels", "verified check trust", "verified", {"bg": "#1D9BF0", "fg": "#FFFFFF"}),
    ("Sold out stamp", "Badges & labels", "sold out stamp", "stamp", {"text": "SOLD OUT", "fg": "#D7263D"}),
    ("Approved stamp", "Badges & labels", "approved stamp ok", "stamp", {"text": "APPROVED", "fg": "#15803D"}),
    ("Bonus badge", "Badges & labels", "bonus extra gift", "ribbon", {"text": "BONUS", "bg": "#DB2777", "fg": "#FFFFFF"}),
    ("Must see", "Badges & labels", "must see important", "tag", {"text": "MUST SEE", "bg": "#111827", "fg": "#FFD84D", "bg2": "#FFD84D", "fg2": "#111827"}),
    ("Step 1", "Badges & labels", "step number one tutorial", "number", {"text": "1", "bg": "#5B5BD6"}),
    ("Step 2", "Badges & labels", "step number two tutorial", "number", {"text": "2", "bg": "#0EA5E9"}),
    ("Step 3", "Badges & labels", "step number three tutorial", "number", {"text": "3", "bg": "#10B981"}),
    ("Step 4", "Badges & labels", "step number four tutorial", "number", {"text": "4", "bg": "#F59E0B"}),
    ("Step 5", "Badges & labels", "step number five tutorial", "number", {"text": "5", "bg": "#EF4444"}),
    # --- Arrows & callouts ---
    ("Bold arrow right", "Arrows & callouts", "arrow direction next point", "arrow", {"angle": 0, "bg": "#FF3B30"}),
    ("Bold arrow left", "Arrows & callouts", "arrow direction back point", "arrow", {"angle": 180, "bg": "#FF3B30"}),
    ("Bold arrow up", "Arrows & callouts", "arrow direction up point", "arrow", {"angle": 90, "bg": "#FFD60A"}),
    ("Bold arrow down", "Arrows & callouts", "arrow direction down point", "arrow", {"angle": 270, "bg": "#FFD60A"}),
    ("Curved arrow", "Arrows & callouts", "arrow curve point look", "curve_arrow", {"bg": "#FF3B30"}),
    ("Curved arrow white", "Arrows & callouts", "arrow curve point look", "curve_arrow", {"bg": "#FFFFFF"}),
    ("Circle callout red", "Arrows & callouts", "circle highlight ring look here", "ring", {"bg": "#FF3B30"}),
    ("Circle callout yellow", "Arrows & callouts", "circle highlight ring look here", "ring", {"bg": "#FFD60A"}),
    ("Click here", "Arrows & callouts", "click here cta arrow", "label_arrow", {"text": "CLICK HERE", "bg": "#FF3B30", "fg": "#FFFFFF"}),
    ("Look here", "Arrows & callouts", "look here callout arrow", "label_arrow", {"text": "LOOK HERE", "bg": "#FFD60A", "fg": "#1A1A1A"}),
    ("Marker underline", "Arrows & callouts", "underline swoosh highlight", "swoosh", {"bg": "#FFD60A"}),
    ("Exclamation callout", "Arrows & callouts", "alert attention important", "icon_circle", {"icon": "exclaim", "bg": "#FF9F0A", "fg": "#FFFFFF"}),
    ("Info callout", "Arrows & callouts", "info note explain", "icon_circle", {"icon": "info", "bg": "#0A84FF", "fg": "#FFFFFF"}),
    # --- Shapes ---
    ("Circle shape", "Shapes", "circle dot shape", "shape", {"shape": "circle", "bg": "#5B5BD6"}),
    ("Rounded square", "Shapes", "square shape box", "shape", {"shape": "square", "bg": "#10B981"}),
    ("Star shape", "Shapes", "star shape", "shape", {"shape": "star", "bg": "#FFC83D"}),
    ("Heart shape", "Shapes", "heart shape love", "shape", {"shape": "heart", "bg": "#FF4D75"}),
    ("Triangle shape", "Shapes", "triangle shape", "shape", {"shape": "triangle", "bg": "#0EA5E9"}),
    ("Hexagon shape", "Shapes", "hexagon shape", "shape", {"shape": "hexagon", "bg": "#F97316"}),
    ("Diamond shape", "Shapes", "diamond rhombus shape", "shape", {"shape": "diamond", "bg": "#A855F7"}),
    ("Ring outline", "Shapes", "ring outline circle frame", "shape", {"shape": "ring", "bg": "#FFFFFF"}),
    ("Lower third bar", "Shapes", "bar plate lower third name", "shape", {"shape": "bar", "bg": "#111827"}),
    ("Gradient blob", "Shapes", "blob organic gradient", "shape", {"shape": "blob", "bg": "#7B5CFF", "bg2": "#FF5FA2"}),
    ("Sparkle shape", "Shapes", "sparkle twinkle shine", "shape", {"shape": "sparkle", "bg": "#FFFFFF"}),
    ("Cloud shape", "Shapes", "cloud weather soft", "shape", {"shape": "cloud", "bg": "#FFFFFF"}),
    # --- Speech bubbles ---
    ("Speech bubble round", "Speech bubbles", "talk say bubble comic", "bubble", {"text": "", "bg": "#FFFFFF", "tail": "left"}),
    ("Speech bubble right", "Speech bubbles", "talk say bubble comic", "bubble", {"text": "", "bg": "#FFFFFF", "tail": "right"}),
    ("Thinking cloud", "Speech bubbles", "think thought cloud bubble", "thought", {"text": "", "bg": "#FFFFFF"}),
    ("Shout bubble", "Speech bubbles", "shout yell comic spiky", "burst", {"text": "", "bg": "#FFFFFF", "edge": "#151515", "fg": "#151515"}),
    ("Chat bubble blue", "Speech bubbles", "message text chat imessage", "chat", {"text": "", "bg": "#0A84FF", "tail": "right"}),
    ("Chat bubble grey", "Speech bubbles", "message text chat reply", "chat", {"text": "", "bg": "#E9E9EB", "tail": "left"}),
    ("Hello bubble", "Speech bubbles", "hello hi greeting bubble", "bubble", {"text": "Hello!", "bg": "#FFFFFF", "fg": "#151515", "tail": "left"}),
    ("Hmm bubble", "Speech bubbles", "hmm thinking bubble", "thought", {"text": "Hmm…", "bg": "#FFFFFF", "fg": "#151515"}),
    ("OMG bubble", "Speech bubbles", "omg shock bubble", "bubble", {"text": "OMG!", "bg": "#FFE45C", "fg": "#151515", "tail": "right"}),
    ("LOL bubble", "Speech bubbles", "lol funny laugh bubble", "chat", {"text": "LOL", "bg": "#34C759", "fg": "#FFFFFF", "tail": "left"}),
    ("Boom comic", "Speech bubbles", "boom comic explosion impact", "burst", {"text": "BOOM!", "bg": "#FFD60A", "fg": "#D7263D", "edge": "#151515"}),
    ("Pow comic", "Speech bubbles", "pow comic punch impact", "burst", {"text": "POW!", "bg": "#00C2FF", "fg": "#FFFFFF", "edge": "#151515"}),
]

CATEGORY_ORDER = ["Smileys", "Gestures", "Hearts", "Animals & nature", "Food", "Travel & places", "Objects",
                  "Symbols", "Arrows & callouts", "Badges & labels", "Social", "Shapes", "Speech bubbles", "Seasonal"]
